// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAnalyticsKPIs = `-- name: GetAnalyticsKPIs :one
SELECT
    COALESCE(SUM(t.price_paid), 0)::NUMERIC AS total_raised,
    COUNT(t.id)::INT AS tickets_sold,
    COUNT(DISTINCT t.user_id)::INT AS unique_buyers
FROM
    tickets t
    JOIN raffle_items ri ON ri.id = t.raffle_item_id
WHERE
    ri.created_by = $1
    AND t.purchased_at >= $2
    AND t.purchased_at < $3
`

type GetAnalyticsKPIsParams struct {
	NonprofitID uuid.NullUUID `json:"nonprofit_id"`
	WindowStart time.Time     `json:"window_start"`
	WindowEnd   time.Time     `json:"window_end"`
}

type GetAnalyticsKPIsRow struct {
	TotalRaised  string `json:"total_raised"`
	TicketsSold  int32  `json:"tickets_sold"`
	UniqueBuyers int32  `json:"unique_buyers"`
}

// All analytics queries take a nonprofit_id and a time window (window_start).
// The handler computes the previous-period window for trend comparisons.
// ── KPIs ──────────────────────────────────────────────────────────────────────
// Total raised, tickets sold, and distinct buyers in a window.
func (q *Queries) GetAnalyticsKPIs(ctx context.Context, arg GetAnalyticsKPIsParams) (GetAnalyticsKPIsRow, error) {
	row := q.db.QueryRowContext(ctx, getAnalyticsKPIs, arg.NonprofitID, arg.WindowStart, arg.WindowEnd)
	var i GetAnalyticsKPIsRow
	err := row.Scan(&i.TotalRaised, &i.TicketsSold, &i.UniqueBuyers)
	return i, err
}

const getBuyerBreakdown = `-- name: GetBuyerBreakdown :one
WITH window_buyers AS (
    SELECT
        DISTINCT t.user_id
    FROM
        tickets t
        JOIN raffle_items ri ON ri.id = t.raffle_item_id
    WHERE
        ri.created_by = $1
        AND t.purchased_at >= $2
        AND t.purchased_at < $3
),
prior_buyers AS (
    SELECT
        DISTINCT t.user_id
    FROM
        tickets t
        JOIN raffle_items ri ON ri.id = t.raffle_item_id
    WHERE
        ri.created_by = $1
        AND t.purchased_at < $2
)
SELECT
    COUNT(*) FILTER (
        WHERE
            wb.user_id IN (
                SELECT
                    user_id
                FROM
                    prior_buyers
            )
    )::INT AS repeat_buyers,
    COUNT(*) FILTER (
        WHERE
            wb.user_id NOT IN (
                SELECT
                    user_id
                FROM
                    prior_buyers
            )
    )::INT AS first_time_buyers,
    COUNT(*) FILTER (
        WHERE
            wb.user_id IN (
                SELECT
                    user_id
                FROM
                    org_follows
                WHERE
                    nonprofit_id = $1
            )
    )::INT AS follower_buyers,
    COUNT(*)::INT AS total_buyers
FROM
    window_buyers wb
`

type GetBuyerBreakdownParams struct {
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	WindowStart time.Time `json:"window_start"`
	WindowEnd   time.Time `json:"window_end"`
}

type GetBuyerBreakdownRow struct {
	RepeatBuyers    int32 `json:"repeat_buyers"`
	FirstTimeBuyers int32 `json:"first_time_buyers"`
	FollowerBuyers  int32 `json:"follower_buyers"`
	TotalBuyers     int32 `json:"total_buyers"`
}

// ── Buyer breakdown (repeat vs first-time vs from followers) ───────────────────
// Classifies buyers in the window:
//
//	repeat       = bought from this org before the window too
//	first_time   = first ever purchase from this org is in the window
//	from_follower = buyer follows the org
func (q *Queries) GetBuyerBreakdown(ctx context.Context, arg GetBuyerBreakdownParams) (GetBuyerBreakdownRow, error) {
	row := q.db.QueryRowContext(ctx, getBuyerBreakdown, arg.NonprofitID, arg.WindowStart, arg.WindowEnd)
	var i GetBuyerBreakdownRow
	err := row.Scan(
		&i.RepeatBuyers,
		&i.FirstTimeBuyers,
		&i.FollowerBuyers,
		&i.TotalBuyers,
	)
	return i, err
}

const getConversionByTicketStrategy = `-- name: GetConversionByTicketStrategy :many
SELECT
    ri.ticket_strategy,
    ri.ticket_price,
    COUNT(DISTINCT rv.id)::INT AS views,
    COUNT(DISTINCT t.id)::INT AS tickets_sold
FROM
    raffle_items ri
    LEFT JOIN raffle_views rv ON rv.raffle_item_id = ri.id
    LEFT JOIN tickets t ON t.raffle_item_id = ri.id
WHERE
    ri.created_by = $1
GROUP BY
    ri.ticket_strategy,
    ri.ticket_price
`

type GetConversionByTicketStrategyRow struct {
	TicketStrategy TicketStrategy `json:"ticket_strategy"`
	TicketPrice    sql.NullString `json:"ticket_price"`
	Views          int32          `json:"views"`
	TicketsSold    int32          `json:"tickets_sold"`
}

// ── Pricing insight support (PWP vs fixed performance) ─────────────────────────
// Feeds the automated "your $5 raffles convert better" style insight.
func (q *Queries) GetConversionByTicketStrategy(ctx context.Context, nonprofitID uuid.NullUUID) ([]GetConversionByTicketStrategyRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversionByTicketStrategy, nonprofitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConversionByTicketStrategyRow{}
	for rows.Next() {
		var i GetConversionByTicketStrategyRow
		if err := rows.Scan(
			&i.TicketStrategy,
			&i.TicketPrice,
			&i.Views,
			&i.TicketsSold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversionStats = `-- name: GetConversionStats :one
WITH org_views AS (
    SELECT
        COUNT(*)::INT AS views
    FROM
        raffle_views rv
        JOIN raffle_items ri ON ri.id = rv.raffle_item_id
    WHERE
        ri.created_by = $1
        AND rv.created_at >= $2
        AND rv.created_at < $3
),
org_buyers AS (
    SELECT
        COUNT(DISTINCT t.user_id)::INT AS buyers
    FROM
        tickets t
        JOIN raffle_items ri ON ri.id = t.raffle_item_id
    WHERE
        ri.created_by = $1
        AND t.purchased_at >= $2
        AND t.purchased_at < $3
)
SELECT
    (
        SELECT
            views
        FROM
            org_views
    ) AS views,
    (
        SELECT
            buyers
        FROM
            org_buyers
    ) AS buyers
`

type GetConversionStatsParams struct {
	NonprofitID uuid.NullUUID `json:"nonprofit_id"`
	WindowStart time.Time     `json:"window_start"`
	WindowEnd   time.Time     `json:"window_end"`
}

type GetConversionStatsRow struct {
	Views  int32 `json:"views"`
	Buyers int32 `json:"buyers"`
}

// ── Conversion (views → purchases) ─────────────────────────────────────────────
func (q *Queries) GetConversionStats(ctx context.Context, arg GetConversionStatsParams) (GetConversionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getConversionStats, arg.NonprofitID, arg.WindowStart, arg.WindowEnd)
	var i GetConversionStatsRow
	err := row.Scan(&i.Views, &i.Buyers)
	return i, err
}

const getNewFollowersInWindow = `-- name: GetNewFollowersInWindow :one
SELECT
    COUNT(*)::INT AS count
FROM
    org_follows
WHERE
    nonprofit_id = $1
    AND created_at >= $2
    AND created_at < $3
`

type GetNewFollowersInWindowParams struct {
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	WindowStart time.Time `json:"window_start"`
	WindowEnd   time.Time `json:"window_end"`
}

func (q *Queries) GetNewFollowersInWindow(ctx context.Context, arg GetNewFollowersInWindowParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNewFollowersInWindow, arg.NonprofitID, arg.WindowStart, arg.WindowEnd)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getRevenueByDay = `-- name: GetRevenueByDay :many
SELECT
    DATE_TRUNC('day', t.purchased_at)::DATE AS DAY,
    SUM(t.price_paid)::NUMERIC AS amount
FROM
    tickets t
    JOIN raffle_items ri ON ri.id = t.raffle_item_id
WHERE
    ri.created_by = $1
    AND t.purchased_at >= $2
    AND t.purchased_at < $3
GROUP BY
    DAY
ORDER BY
    DAY
`

type GetRevenueByDayParams struct {
	NonprofitID uuid.NullUUID `json:"nonprofit_id"`
	WindowStart time.Time     `json:"window_start"`
	WindowEnd   time.Time     `json:"window_end"`
}

type GetRevenueByDayRow struct {
	Day    time.Time `json:"day"`
	Amount string    `json:"amount"`
}

// ── Revenue series (bar chart) ────────────────────────────────────────────────
// Daily revenue for the chart. Handler buckets into weeks/months as needed.
func (q *Queries) GetRevenueByDay(ctx context.Context, arg GetRevenueByDayParams) ([]GetRevenueByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, getRevenueByDay, arg.NonprofitID, arg.WindowStart, arg.WindowEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevenueByDayRow{}
	for rows.Next() {
		var i GetRevenueByDayRow
		if err := rows.Scan(&i.Day, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByMonth = `-- name: GetRevenueByMonth :many
SELECT
    DATE_TRUNC('month', t.purchased_at)::DATE AS MONTH,
    SUM(t.price_paid)::NUMERIC AS amount
FROM
    tickets t
    JOIN raffle_items ri ON ri.id = t.raffle_item_id
WHERE
    ri.created_by = $1
    AND t.purchased_at >= $2
GROUP BY
    MONTH
ORDER BY
    MONTH
`

type GetRevenueByMonthParams struct {
	NonprofitID uuid.NullUUID `json:"nonprofit_id"`
	WindowStart time.Time     `json:"window_start"`
}

type GetRevenueByMonthRow struct {
	Month  time.Time `json:"month"`
	Amount string    `json:"amount"`
}

// Monthly buckets for longer ranges (year / all).
func (q *Queries) GetRevenueByMonth(ctx context.Context, arg GetRevenueByMonthParams) ([]GetRevenueByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getRevenueByMonth, arg.NonprofitID, arg.WindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevenueByMonthRow{}
	for rows.Next() {
		var i GetRevenueByMonthRow
		if err := rows.Scan(&i.Month, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopRaffles = `-- name: GetTopRaffles :many
SELECT
    ri.id,
    ri.title,
    ri.tickets_sold,
    ri.max_tickets,
    COALESCE(SUM(t.price_paid), 0)::NUMERIC AS raised
FROM
    raffle_items ri
    LEFT JOIN tickets t ON t.raffle_item_id = ri.id
WHERE
    ri.created_by = $1
    AND ri.created_at >= $2
GROUP BY
    ri.id,
    ri.title,
    ri.tickets_sold,
    ri.max_tickets
ORDER BY
    raised DESC
LIMIT
    $3
`

type GetTopRafflesParams struct {
	NonprofitID uuid.NullUUID `json:"nonprofit_id"`
	WindowStart time.Time     `json:"window_start"`
	ResultLimit int32         `json:"result_limit"`
}

type GetTopRafflesRow struct {
	ID          uuid.UUID     `json:"id"`
	Title       string        `json:"title"`
	TicketsSold int32         `json:"tickets_sold"`
	MaxTickets  sql.NullInt32 `json:"max_tickets"`
	Raised      string        `json:"raised"`
}

// ── Top performing raffles ────────────────────────────────────────────────────
func (q *Queries) GetTopRaffles(ctx context.Context, arg GetTopRafflesParams) ([]GetTopRafflesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopRaffles, arg.NonprofitID, arg.WindowStart, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopRafflesRow{}
	for rows.Next() {
		var i GetTopRafflesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TicketsSold,
			&i.MaxTickets,
			&i.Raised,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
