// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT
    s.id AS session_id,
    s."userId" AS user_id,
    s."expiresAt" AS expires_at,
    u.name AS user_name,
    u.email AS user_email
FROM
    "session" s
    JOIN users u ON u.id = s."userId"
WHERE
    s.token = $1
`

type GetSessionByTokenRow struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	UserName  string    `json:"user_name"`
	UserEmail string    `json:"user_email"`
}

// Validates a better-auth session. Columns are aliased to snake_case so sqlc
// generates clean Go field names from the camelCase better-auth schema.
func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.UserName,
		&i.UserEmail,
	)
	return i, err
}

const getUserMembership = `-- name: GetUserMembership :one
SELECT
    nonprofit_id,
    role
FROM
    nonprofit_users
WHERE
    user_id = $1
ORDER BY
    created_at
LIMIT
    1
`

type GetUserMembershipRow struct {
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	Role        string    `json:"role"`
}

// The nonprofit a user manages, if any. No row = participant (not an org member).
// A user could belong to several orgs; we take one for now (org-switching later).
func (q *Queries) GetUserMembership(ctx context.Context, userID uuid.UUID) (GetUserMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, getUserMembership, userID)
	var i GetUserMembershipRow
	err := row.Scan(&i.NonprofitID, &i.Role)
	return i, err
}
