// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO
    categories (
        parent_id,
        path,
        depth,
        name,
        slug,
        icon,
        sort_order,
        attribute_schema
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id, parent_id, path, depth, name, slug, icon, sort_order, attribute_schema, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	ParentID        uuid.NullUUID         `json:"parent_id"`
	Path            string                `json:"path"`
	Depth           int32                 `json:"depth"`
	Name            string                `json:"name"`
	Slug            string                `json:"slug"`
	Icon            sql.NullString        `json:"icon"`
	SortOrder       int32                 `json:"sort_order"`
	AttributeSchema pqtype.NullRawMessage `json:"attribute_schema"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.ParentID,
		arg.Path,
		arg.Depth,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.SortOrder,
		arg.AttributeSchema,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Path,
		&i.Depth,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.SortOrder,
		&i.AttributeSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateCategory = `-- name: DeactivateCategory :exec
UPDATE
    categories
SET
    is_active = FALSE
WHERE
    id = $1
`

func (q *Queries) DeactivateCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT
    id, parent_id, path, depth, name, slug, icon, sort_order, attribute_schema, is_active, created_at, updated_at
FROM
    categories
WHERE
    id = $1
    AND is_active = TRUE
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Path,
		&i.Depth,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.SortOrder,
		&i.AttributeSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT
    id, parent_id, path, depth, name, slug, icon, sort_order, attribute_schema, is_active, created_at, updated_at
FROM
    categories
WHERE
    slug = $1
    AND is_active = TRUE
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Path,
		&i.Depth,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.SortOrder,
		&i.AttributeSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllActiveCategories = `-- name: ListAllActiveCategories :many
SELECT
    id, parent_id, path, depth, name, slug, icon, sort_order, attribute_schema, is_active, created_at, updated_at
FROM
    categories
WHERE
    is_active = TRUE
ORDER BY
    depth,
    sort_order,
    name
`

func (q *Queries) ListAllActiveCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listAllActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Path,
			&i.Depth,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.SortOrder,
			&i.AttributeSchema,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryItemCounts = `-- name: ListCategoryItemCounts :many
SELECT
    id, name, slug, path, parent_id, depth, icon, sort_order, attribute_schema, active_item_count
FROM
    v_category_item_counts
`

// Powers the browse sidebar (item counts include subcategories).
func (q *Queries) ListCategoryItemCounts(ctx context.Context) ([]VCategoryItemCount, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryItemCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VCategoryItemCount{}
	for rows.Next() {
		var i VCategoryItemCount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Path,
			&i.ParentID,
			&i.Depth,
			&i.Icon,
			&i.SortOrder,
			&i.AttributeSchema,
			&i.ActiveItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildCategories = `-- name: ListChildCategories :many
SELECT
    id, parent_id, path, depth, name, slug, icon, sort_order, attribute_schema, is_active, created_at, updated_at
FROM
    categories
WHERE
    parent_id = $1
    AND is_active = TRUE
ORDER BY
    sort_order,
    name
`

func (q *Queries) ListChildCategories(ctx context.Context, parentID uuid.NullUUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listChildCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Path,
			&i.Depth,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.SortOrder,
			&i.AttributeSchema,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCategories = `-- name: ListRootCategories :many
SELECT
    id, parent_id, path, depth, name, slug, icon, sort_order, attribute_schema, is_active, created_at, updated_at
FROM
    categories
WHERE
    parent_id IS NULL
    AND is_active = TRUE
ORDER BY
    sort_order,
    name
`

func (q *Queries) ListRootCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listRootCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Path,
			&i.Depth,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.SortOrder,
			&i.AttributeSchema,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCategoriesByName = `-- name: SearchCategoriesByName :many
SELECT
    id, parent_id, path, depth, name, slug, icon, sort_order, attribute_schema, is_active, created_at, updated_at
FROM
    categories
WHERE
    is_active = TRUE
    AND name ILIKE '%' || $1 || '%'
ORDER BY
    name
LIMIT
    $2
`

type SearchCategoriesByNameParams struct {
	Query       sql.NullString `json:"query"`
	ResultLimit int32          `json:"result_limit"`
}

func (q *Queries) SearchCategoriesByName(ctx context.Context, arg SearchCategoriesByNameParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, searchCategoriesByName, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Path,
			&i.Depth,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.SortOrder,
			&i.AttributeSchema,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE
    categories
SET
    name = $2,
    icon = $3,
    sort_order = $4,
    attribute_schema = $5
WHERE
    id = $1
RETURNING
    id, parent_id, path, depth, name, slug, icon, sort_order, attribute_schema, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID              uuid.UUID             `json:"id"`
	Name            string                `json:"name"`
	Icon            sql.NullString        `json:"icon"`
	SortOrder       int32                 `json:"sort_order"`
	AttributeSchema pqtype.NullRawMessage `json:"attribute_schema"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.SortOrder,
		arg.AttributeSchema,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Path,
		&i.Depth,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.SortOrder,
		&i.AttributeSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
