// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: draws.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const claimPrize = `-- name: ClaimPrize :one
UPDATE
    draw_winners
SET
    prize_claimed = TRUE,
    claimed_at = NOW()
WHERE
    id = $1
    AND user_id = $2
RETURNING
    id, draw_result_id, pull_index, rank, ticket_id, ticket_number, user_id, prize_title, prize_description, prize_value_cents, revealed_at_ms, prize_claimed, claimed_at, created_at
`

type ClaimPrizeParams struct {
	WinnerID uuid.UUID `json:"winner_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) ClaimPrize(ctx context.Context, arg ClaimPrizeParams) (DrawWinner, error) {
	row := q.db.QueryRowContext(ctx, claimPrize, arg.WinnerID, arg.UserID)
	var i DrawWinner
	err := row.Scan(
		&i.ID,
		&i.DrawResultID,
		&i.PullIndex,
		&i.Rank,
		&i.TicketID,
		&i.TicketNumber,
		&i.UserID,
		&i.PrizeTitle,
		&i.PrizeDescription,
		&i.PrizeValueCents,
		&i.RevealedAtMs,
		&i.PrizeClaimed,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const completeDrawResult = `-- name: CompleteDrawResult :exec
UPDATE
    draw_results
SET
    STATUS = 'completed'
WHERE
    raffle_item_id = $1
`

func (q *Queries) CompleteDrawResult(ctx context.Context, raffleItemID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, completeDrawResult, raffleItemID)
	return err
}

const countUserWins = `-- name: CountUserWins :one
SELECT
    COUNT(*)::INT AS count
FROM
    draw_winners
WHERE
    user_id = $1
`

func (q *Queries) CountUserWins(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countUserWins, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createDrawResult = `-- name: CreateDrawResult :one
INSERT INTO
    draw_results (
        raffle_item_id,
        draw_strategy,
        reveal_order,
        winner_count,
        commitment_hash,
        total_tickets,
        total_participants,
        verification_url,
        STATUS
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    id, raffle_item_id, draw_strategy, reveal_order, winner_count, commitment_hash, seed, draw_started_at, draw_duration_ms, total_tickets, total_participants, verification_url, status, created_at, updated_at
`

type CreateDrawResultParams struct {
	RaffleItemID      uuid.UUID      `json:"raffle_item_id"`
	DrawStrategy      DrawStrategy   `json:"draw_strategy"`
	RevealOrder       string         `json:"reveal_order"`
	WinnerCount       int32          `json:"winner_count"`
	CommitmentHash    string         `json:"commitment_hash"`
	TotalTickets      int32          `json:"total_tickets"`
	TotalParticipants int32          `json:"total_participants"`
	VerificationUrl   sql.NullString `json:"verification_url"`
	Status            string         `json:"status"`
}

// ── Draw results ──────────────────────────────────────────────────────────────
func (q *Queries) CreateDrawResult(ctx context.Context, arg CreateDrawResultParams) (DrawResult, error) {
	row := q.db.QueryRowContext(ctx, createDrawResult,
		arg.RaffleItemID,
		arg.DrawStrategy,
		arg.RevealOrder,
		arg.WinnerCount,
		arg.CommitmentHash,
		arg.TotalTickets,
		arg.TotalParticipants,
		arg.VerificationUrl,
		arg.Status,
	)
	var i DrawResult
	err := row.Scan(
		&i.ID,
		&i.RaffleItemID,
		&i.DrawStrategy,
		&i.RevealOrder,
		&i.WinnerCount,
		&i.CommitmentHash,
		&i.Seed,
		&i.DrawStartedAt,
		&i.DrawDurationMs,
		&i.TotalTickets,
		&i.TotalParticipants,
		&i.VerificationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDrawWinner = `-- name: CreateDrawWinner :one
INSERT INTO
    draw_winners (
        draw_result_id,
        pull_index,
        rank,
        ticket_id,
        ticket_number,
        user_id,
        prize_title,
        prize_description,
        prize_value_cents,
        revealed_at_ms
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id, draw_result_id, pull_index, rank, ticket_id, ticket_number, user_id, prize_title, prize_description, prize_value_cents, revealed_at_ms, prize_claimed, claimed_at, created_at
`

type CreateDrawWinnerParams struct {
	DrawResultID     uuid.UUID      `json:"draw_result_id"`
	PullIndex        int32          `json:"pull_index"`
	Rank             int32          `json:"rank"`
	TicketID         uuid.UUID      `json:"ticket_id"`
	TicketNumber     int32          `json:"ticket_number"`
	UserID           uuid.UUID      `json:"user_id"`
	PrizeTitle       string         `json:"prize_title"`
	PrizeDescription sql.NullString `json:"prize_description"`
	PrizeValueCents  sql.NullInt32  `json:"prize_value_cents"`
	RevealedAtMs     int32          `json:"revealed_at_ms"`
}

// ── Draw winners ──────────────────────────────────────────────────────────────
func (q *Queries) CreateDrawWinner(ctx context.Context, arg CreateDrawWinnerParams) (DrawWinner, error) {
	row := q.db.QueryRowContext(ctx, createDrawWinner,
		arg.DrawResultID,
		arg.PullIndex,
		arg.Rank,
		arg.TicketID,
		arg.TicketNumber,
		arg.UserID,
		arg.PrizeTitle,
		arg.PrizeDescription,
		arg.PrizeValueCents,
		arg.RevealedAtMs,
	)
	var i DrawWinner
	err := row.Scan(
		&i.ID,
		&i.DrawResultID,
		&i.PullIndex,
		&i.Rank,
		&i.TicketID,
		&i.TicketNumber,
		&i.UserID,
		&i.PrizeTitle,
		&i.PrizeDescription,
		&i.PrizeValueCents,
		&i.RevealedAtMs,
		&i.PrizeClaimed,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDrawResultForRaffle = `-- name: GetDrawResultForRaffle :one
SELECT
    id, raffle_item_id, draw_strategy, reveal_order, winner_count, commitment_hash, seed, draw_started_at, draw_duration_ms, total_tickets, total_participants, verification_url, status, created_at, updated_at
FROM
    draw_results
WHERE
    raffle_item_id = $1
`

func (q *Queries) GetDrawResultForRaffle(ctx context.Context, raffleItemID uuid.UUID) (DrawResult, error) {
	row := q.db.QueryRowContext(ctx, getDrawResultForRaffle, raffleItemID)
	var i DrawResult
	err := row.Scan(
		&i.ID,
		&i.RaffleItemID,
		&i.DrawStrategy,
		&i.RevealOrder,
		&i.WinnerCount,
		&i.CommitmentHash,
		&i.Seed,
		&i.DrawStartedAt,
		&i.DrawDurationMs,
		&i.TotalTickets,
		&i.TotalParticipants,
		&i.VerificationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWinForRaffle = `-- name: GetUserWinForRaffle :one
SELECT
    dw.id, dw.draw_result_id, dw.pull_index, dw.rank, dw.ticket_id, dw.ticket_number, dw.user_id, dw.prize_title, dw.prize_description, dw.prize_value_cents, dw.revealed_at_ms, dw.prize_claimed, dw.claimed_at, dw.created_at
FROM
    draw_winners dw
    JOIN draw_results dr ON dr.id = dw.draw_result_id
WHERE
    dr.raffle_item_id = $1
    AND dw.user_id = $2
LIMIT
    1
`

type GetUserWinForRaffleParams struct {
	RaffleItemID uuid.UUID `json:"raffle_item_id"`
	UserID       uuid.UUID `json:"user_id"`
}

// Did this user win anything in this raffle?
func (q *Queries) GetUserWinForRaffle(ctx context.Context, arg GetUserWinForRaffleParams) (DrawWinner, error) {
	row := q.db.QueryRowContext(ctx, getUserWinForRaffle, arg.RaffleItemID, arg.UserID)
	var i DrawWinner
	err := row.Scan(
		&i.ID,
		&i.DrawResultID,
		&i.PullIndex,
		&i.Rank,
		&i.TicketID,
		&i.TicketNumber,
		&i.UserID,
		&i.PrizeTitle,
		&i.PrizeDescription,
		&i.PrizeValueCents,
		&i.RevealedAtMs,
		&i.PrizeClaimed,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationData = `-- name: GetVerificationData :one
SELECT
    dr.commitment_hash,
    dr.seed,
    dr.draw_strategy,
    dr.reveal_order,
    dr.winner_count,
    dr.raffle_item_id
FROM
    draw_results dr
WHERE
    dr.raffle_item_id = $1
`

type GetVerificationDataRow struct {
	CommitmentHash string         `json:"commitment_hash"`
	Seed           sql.NullString `json:"seed"`
	DrawStrategy   DrawStrategy   `json:"draw_strategy"`
	RevealOrder    string         `json:"reveal_order"`
	WinnerCount    int32          `json:"winner_count"`
	RaffleItemID   uuid.UUID      `json:"raffle_item_id"`
}

// ── Verification ──────────────────────────────────────────────────────────────
// Everything the client needs to independently verify the draw.
func (q *Queries) GetVerificationData(ctx context.Context, raffleItemID uuid.UUID) (GetVerificationDataRow, error) {
	row := q.db.QueryRowContext(ctx, getVerificationData, raffleItemID)
	var i GetVerificationDataRow
	err := row.Scan(
		&i.CommitmentHash,
		&i.Seed,
		&i.DrawStrategy,
		&i.RevealOrder,
		&i.WinnerCount,
		&i.RaffleItemID,
	)
	return i, err
}

const listDrawWinners = `-- name: ListDrawWinners :many
SELECT
    dw.id, dw.draw_result_id, dw.pull_index, dw.rank, dw.ticket_id, dw.ticket_number, dw.user_id, dw.prize_title, dw.prize_description, dw.prize_value_cents, dw.revealed_at_ms, dw.prize_claimed, dw.claimed_at, dw.created_at,
    u.name AS user_name
FROM
    draw_winners dw
    JOIN users u ON u.id = dw.user_id
WHERE
    dw.draw_result_id = $1
ORDER BY
    dw.pull_index
`

type ListDrawWinnersRow struct {
	ID               uuid.UUID      `json:"id"`
	DrawResultID     uuid.UUID      `json:"draw_result_id"`
	PullIndex        int32          `json:"pull_index"`
	Rank             int32          `json:"rank"`
	TicketID         uuid.UUID      `json:"ticket_id"`
	TicketNumber     int32          `json:"ticket_number"`
	UserID           uuid.UUID      `json:"user_id"`
	PrizeTitle       string         `json:"prize_title"`
	PrizeDescription sql.NullString `json:"prize_description"`
	PrizeValueCents  sql.NullInt32  `json:"prize_value_cents"`
	RevealedAtMs     int32          `json:"revealed_at_ms"`
	PrizeClaimed     bool           `json:"prize_claimed"`
	ClaimedAt        sql.NullTime   `json:"claimed_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UserName         string         `json:"user_name"`
}

// The frozen ordered result the reveal engine animates (pull order).
func (q *Queries) ListDrawWinners(ctx context.Context, drawResultID uuid.UUID) ([]ListDrawWinnersRow, error) {
	rows, err := q.db.QueryContext(ctx, listDrawWinners, drawResultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDrawWinnersRow{}
	for rows.Next() {
		var i ListDrawWinnersRow
		if err := rows.Scan(
			&i.ID,
			&i.DrawResultID,
			&i.PullIndex,
			&i.Rank,
			&i.TicketID,
			&i.TicketNumber,
			&i.UserID,
			&i.PrizeTitle,
			&i.PrizeDescription,
			&i.PrizeValueCents,
			&i.RevealedAtMs,
			&i.PrizeClaimed,
			&i.ClaimedAt,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrawWinnersByRaffle = `-- name: ListDrawWinnersByRaffle :many
SELECT
    dw.id, dw.draw_result_id, dw.pull_index, dw.rank, dw.ticket_id, dw.ticket_number, dw.user_id, dw.prize_title, dw.prize_description, dw.prize_value_cents, dw.revealed_at_ms, dw.prize_claimed, dw.claimed_at, dw.created_at
FROM
    draw_winners dw
    JOIN draw_results dr ON dr.id = dw.draw_result_id
WHERE
    dr.raffle_item_id = $1
ORDER BY
    dw.pull_index
`

func (q *Queries) ListDrawWinnersByRaffle(ctx context.Context, raffleItemID uuid.UUID) ([]DrawWinner, error) {
	rows, err := q.db.QueryContext(ctx, listDrawWinnersByRaffle, raffleItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DrawWinner{}
	for rows.Next() {
		var i DrawWinner
		if err := rows.Scan(
			&i.ID,
			&i.DrawResultID,
			&i.PullIndex,
			&i.Rank,
			&i.TicketID,
			&i.TicketNumber,
			&i.UserID,
			&i.PrizeTitle,
			&i.PrizeDescription,
			&i.PrizeValueCents,
			&i.RevealedAtMs,
			&i.PrizeClaimed,
			&i.ClaimedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclaimedPrizesForNonprofit = `-- name: ListUnclaimedPrizesForNonprofit :many
SELECT
    dw.id, dw.draw_result_id, dw.pull_index, dw.rank, dw.ticket_id, dw.ticket_number, dw.user_id, dw.prize_title, dw.prize_description, dw.prize_value_cents, dw.revealed_at_ms, dw.prize_claimed, dw.claimed_at, dw.created_at,
    ri.title AS raffle_title,
    ri.id AS raffle_item_id
FROM
    draw_winners dw
    JOIN draw_results dr ON dr.id = dw.draw_result_id
    JOIN raffle_items ri ON ri.id = dr.raffle_item_id
WHERE
    ri.created_by = $1
    AND dw.prize_claimed = FALSE
ORDER BY
    dw.created_at
`

type ListUnclaimedPrizesForNonprofitRow struct {
	ID               uuid.UUID      `json:"id"`
	DrawResultID     uuid.UUID      `json:"draw_result_id"`
	PullIndex        int32          `json:"pull_index"`
	Rank             int32          `json:"rank"`
	TicketID         uuid.UUID      `json:"ticket_id"`
	TicketNumber     int32          `json:"ticket_number"`
	UserID           uuid.UUID      `json:"user_id"`
	PrizeTitle       string         `json:"prize_title"`
	PrizeDescription sql.NullString `json:"prize_description"`
	PrizeValueCents  sql.NullInt32  `json:"prize_value_cents"`
	RevealedAtMs     int32          `json:"revealed_at_ms"`
	PrizeClaimed     bool           `json:"prize_claimed"`
	ClaimedAt        sql.NullTime   `json:"claimed_at"`
	CreatedAt        time.Time      `json:"created_at"`
	RaffleTitle      string         `json:"raffle_title"`
	RaffleItemID     uuid.UUID      `json:"raffle_item_id"`
}

// Dashboard alert: winners who haven't claimed.
func (q *Queries) ListUnclaimedPrizesForNonprofit(ctx context.Context, createdBy uuid.NullUUID) ([]ListUnclaimedPrizesForNonprofitRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnclaimedPrizesForNonprofit, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnclaimedPrizesForNonprofitRow{}
	for rows.Next() {
		var i ListUnclaimedPrizesForNonprofitRow
		if err := rows.Scan(
			&i.ID,
			&i.DrawResultID,
			&i.PullIndex,
			&i.Rank,
			&i.TicketID,
			&i.TicketNumber,
			&i.UserID,
			&i.PrizeTitle,
			&i.PrizeDescription,
			&i.PrizeValueCents,
			&i.RevealedAtMs,
			&i.PrizeClaimed,
			&i.ClaimedAt,
			&i.CreatedAt,
			&i.RaffleTitle,
			&i.RaffleItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWins = `-- name: ListUserWins :many
SELECT
    dw.id, dw.draw_result_id, dw.pull_index, dw.rank, dw.ticket_id, dw.ticket_number, dw.user_id, dw.prize_title, dw.prize_description, dw.prize_value_cents, dw.revealed_at_ms, dw.prize_claimed, dw.claimed_at, dw.created_at,
    ri.id AS raffle_item_id,
    ri.title AS raffle_title,
    ri.image_urls,
    n.name AS nonprofit_name
FROM
    draw_winners dw
    JOIN draw_results dr ON dr.id = dw.draw_result_id
    JOIN raffle_items ri ON ri.id = dr.raffle_item_id
    LEFT JOIN nonprofits n ON n.id = ri.created_by
WHERE
    dw.user_id = $1
ORDER BY
    dw.created_at DESC
`

type ListUserWinsRow struct {
	ID               uuid.UUID      `json:"id"`
	DrawResultID     uuid.UUID      `json:"draw_result_id"`
	PullIndex        int32          `json:"pull_index"`
	Rank             int32          `json:"rank"`
	TicketID         uuid.UUID      `json:"ticket_id"`
	TicketNumber     int32          `json:"ticket_number"`
	UserID           uuid.UUID      `json:"user_id"`
	PrizeTitle       string         `json:"prize_title"`
	PrizeDescription sql.NullString `json:"prize_description"`
	PrizeValueCents  sql.NullInt32  `json:"prize_value_cents"`
	RevealedAtMs     int32          `json:"revealed_at_ms"`
	PrizeClaimed     bool           `json:"prize_claimed"`
	ClaimedAt        sql.NullTime   `json:"claimed_at"`
	CreatedAt        time.Time      `json:"created_at"`
	RaffleItemID     uuid.UUID      `json:"raffle_item_id"`
	RaffleTitle      string         `json:"raffle_title"`
	ImageUrls        []string       `json:"image_urls"`
	NonprofitName    sql.NullString `json:"nonprofit_name"`
}

// ── User's wins (My Tickets → Won tab) ────────────────────────────────────────
func (q *Queries) ListUserWins(ctx context.Context, userID uuid.UUID) ([]ListUserWinsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserWins, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserWinsRow{}
	for rows.Next() {
		var i ListUserWinsRow
		if err := rows.Scan(
			&i.ID,
			&i.DrawResultID,
			&i.PullIndex,
			&i.Rank,
			&i.TicketID,
			&i.TicketNumber,
			&i.UserID,
			&i.PrizeTitle,
			&i.PrizeDescription,
			&i.PrizeValueCents,
			&i.RevealedAtMs,
			&i.PrizeClaimed,
			&i.ClaimedAt,
			&i.CreatedAt,
			&i.RaffleItemID,
			&i.RaffleTitle,
			pq.Array(&i.ImageUrls),
			&i.NonprofitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCommitmentHash = `-- name: SetCommitmentHash :exec
UPDATE
    draw_results
SET
    commitment_hash = $2
WHERE
    raffle_item_id = $1
`

type SetCommitmentHashParams struct {
	RaffleItemID   uuid.UUID `json:"raffle_item_id"`
	CommitmentHash string    `json:"commitment_hash"`
}

// Published BEFORE sales close (at raffle publish time).
func (q *Queries) SetCommitmentHash(ctx context.Context, arg SetCommitmentHashParams) error {
	_, err := q.db.ExecContext(ctx, setCommitmentHash, arg.RaffleItemID, arg.CommitmentHash)
	return err
}

const startDrawReveal = `-- name: StartDrawReveal :one
UPDATE
    draw_results
SET
    STATUS = 'in_progress',
    draw_started_at = NOW(),
    draw_duration_ms = $2,
    seed = $3
WHERE
    raffle_item_id = $1
RETURNING
    id, raffle_item_id, draw_strategy, reveal_order, winner_count, commitment_hash, seed, draw_started_at, draw_duration_ms, total_tickets, total_participants, verification_url, status, created_at, updated_at
`

type StartDrawRevealParams struct {
	RaffleItemID   uuid.UUID      `json:"raffle_item_id"`
	DrawDurationMs int32          `json:"draw_duration_ms"`
	Seed           sql.NullString `json:"seed"`
}

// Fires the reveal: stamps start time, duration, reveals the seed, sets status.
func (q *Queries) StartDrawReveal(ctx context.Context, arg StartDrawRevealParams) (DrawResult, error) {
	row := q.db.QueryRowContext(ctx, startDrawReveal, arg.RaffleItemID, arg.DrawDurationMs, arg.Seed)
	var i DrawResult
	err := row.Scan(
		&i.ID,
		&i.RaffleItemID,
		&i.DrawStrategy,
		&i.RevealOrder,
		&i.WinnerCount,
		&i.CommitmentHash,
		&i.Seed,
		&i.DrawStartedAt,
		&i.DrawDurationMs,
		&i.TotalTickets,
		&i.TotalParticipants,
		&i.VerificationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
