// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: draws_worker.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDrawResultWithSeed = `-- name: CreateDrawResultWithSeed :one
INSERT INTO
    draw_results (
        raffle_item_id,
        draw_strategy,
        reveal_order,
        winner_count,
        commitment_hash,
        seed,
        total_tickets,
        total_participants,
        STATUS
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        'scheduled'
    )
RETURNING
    id, raffle_item_id, draw_strategy, reveal_order, winner_count, commitment_hash, seed, draw_started_at, draw_duration_ms, total_tickets, total_participants, verification_url, status, created_at, updated_at
`

type CreateDrawResultWithSeedParams struct {
	RaffleItemID      uuid.UUID      `json:"raffle_item_id"`
	DrawStrategy      DrawStrategy   `json:"draw_strategy"`
	RevealOrder       string         `json:"reveal_order"`
	WinnerCount       int32          `json:"winner_count"`
	CommitmentHash    string         `json:"commitment_hash"`
	Seed              sql.NullString `json:"seed"`
	TotalTickets      int32          `json:"total_tickets"`
	TotalParticipants int32          `json:"total_participants"`
}

// Used at publish time: stores the secret seed alongside the public commitment.
// (The API never returns seed until status = 'completed'.) Also used as a dev
// fallback by the worker if a raffle reached its draw time without a result row.
func (q *Queries) CreateDrawResultWithSeed(ctx context.Context, arg CreateDrawResultWithSeedParams) (DrawResult, error) {
	row := q.db.QueryRowContext(ctx, createDrawResultWithSeed,
		arg.RaffleItemID,
		arg.DrawStrategy,
		arg.RevealOrder,
		arg.WinnerCount,
		arg.CommitmentHash,
		arg.Seed,
		arg.TotalTickets,
		arg.TotalParticipants,
	)
	var i DrawResult
	err := row.Scan(
		&i.ID,
		&i.RaffleItemID,
		&i.DrawStrategy,
		&i.RevealOrder,
		&i.WinnerCount,
		&i.CommitmentHash,
		&i.Seed,
		&i.DrawStartedAt,
		&i.DrawDurationMs,
		&i.TotalTickets,
		&i.TotalParticipants,
		&i.VerificationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRaffleDrawing = `-- name: MarkRaffleDrawing :exec
UPDATE
    raffle_items
SET
    STATUS = 'drawing'
WHERE
    id = $1
`

func (q *Queries) MarkRaffleDrawing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markRaffleDrawing, id)
	return err
}

const markRaffleDrawn = `-- name: MarkRaffleDrawn :exec
UPDATE
    raffle_items
SET
    STATUS = 'completed',
    drawn_at = NOW()
WHERE
    id = $1
`

func (q *Queries) MarkRaffleDrawn(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markRaffleDrawn, id)
	return err
}
