// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engagement.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM
    nonprofit_reviews
WHERE
    nonprofit_id = $1
    AND user_id = $2
`

type DeleteReviewParams struct {
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteReview(ctx context.Context, arg DeleteReviewParams) error {
	_, err := q.db.ExecContext(ctx, deleteReview, arg.NonprofitID, arg.UserID)
	return err
}

const followOrg = `-- name: FollowOrg :one
INSERT INTO
    org_follows (user_id, nonprofit_id)
VALUES
    ($1, $2) ON CONFLICT (user_id, nonprofit_id) DO NOTHING
RETURNING
    id, user_id, nonprofit_id, created_at
`

type FollowOrgParams struct {
	UserID      uuid.UUID `json:"user_id"`
	NonprofitID uuid.UUID `json:"nonprofit_id"`
}

// ── Org follows ───────────────────────────────────────────────────────────────
func (q *Queries) FollowOrg(ctx context.Context, arg FollowOrgParams) (OrgFollow, error) {
	row := q.db.QueryRowContext(ctx, followOrg, arg.UserID, arg.NonprofitID)
	var i OrgFollow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NonprofitID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgReviewSummary = `-- name: GetOrgReviewSummary :one
SELECT
    COUNT(*)::INT AS review_count,
    COALESCE(AVG(rating), 0)::NUMERIC(3, 2) AS average_rating
FROM
    nonprofit_reviews
WHERE
    nonprofit_id = $1
`

type GetOrgReviewSummaryRow struct {
	ReviewCount   int32  `json:"review_count"`
	AverageRating string `json:"average_rating"`
}

func (q *Queries) GetOrgReviewSummary(ctx context.Context, nonprofitID uuid.UUID) (GetOrgReviewSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgReviewSummary, nonprofitID)
	var i GetOrgReviewSummaryRow
	err := row.Scan(&i.ReviewCount, &i.AverageRating)
	return i, err
}

const isFollowingOrg = `-- name: IsFollowingOrg :one
SELECT
    EXISTS(
        SELECT
            1
        FROM
            org_follows
        WHERE
            user_id = $1
            AND nonprofit_id = $2
    ) AS following
`

type IsFollowingOrgParams struct {
	UserID      uuid.UUID `json:"user_id"`
	NonprofitID uuid.UUID `json:"nonprofit_id"`
}

func (q *Queries) IsFollowingOrg(ctx context.Context, arg IsFollowingOrgParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFollowingOrg, arg.UserID, arg.NonprofitID)
	var following bool
	err := row.Scan(&following)
	return following, err
}

const isRaffleSaved = `-- name: IsRaffleSaved :one
SELECT
    EXISTS(
        SELECT
            1
        FROM
            saved_raffles
        WHERE
            user_id = $1
            AND raffle_item_id = $2
    ) AS saved
`

type IsRaffleSavedParams struct {
	UserID       uuid.UUID `json:"user_id"`
	RaffleItemID uuid.UUID `json:"raffle_item_id"`
}

func (q *Queries) IsRaffleSaved(ctx context.Context, arg IsRaffleSavedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRaffleSaved, arg.UserID, arg.RaffleItemID)
	var saved bool
	err := row.Scan(&saved)
	return saved, err
}

const listFollowedOrgs = `-- name: ListFollowedOrgs :many
SELECT
    n.id, n.name, n.slug, n.description, n.image, n.address, n.phone, n.ein, n."hasToPay", n.website, n.categories, n.follower_count, n.total_raised_cents, n.raffles_run, n.created_at, n.updated_at,
    of.created_at AS followed_at,
    COALESCE(v."isVerified", FALSE)::bool AS is_verified,
    (
        SELECT
            COUNT(*)
        FROM
            raffle_items ri
        WHERE
            ri.created_by = n.id
            AND ri.status = 'active'::raffle_item_status
    )::INT AS active_raffles
FROM
    org_follows of
    JOIN nonprofits n ON n.id = of.nonprofit_id
    LEFT JOIN LATERAL (
        SELECT
            nv."isVerified"
        FROM
            nonprofit_verifications nv
        WHERE
            nv.nonprofit_id = n.id
        ORDER BY
            nv.created_at DESC
        LIMIT
            1
    ) v ON TRUE
WHERE
    of.user_id = $1
ORDER BY
    of.created_at DESC
`

type ListFollowedOrgsRow struct {
	ID               uuid.UUID      `json:"id"`
	Name             string         `json:"name"`
	Slug             sql.NullString `json:"slug"`
	Description      sql.NullString `json:"description"`
	Image            sql.NullString `json:"image"`
	Address          sql.NullString `json:"address"`
	Phone            sql.NullString `json:"phone"`
	Ein              sql.NullString `json:"ein"`
	HasToPay         bool           `json:"hasToPay"`
	Website          sql.NullString `json:"website"`
	Categories       []string       `json:"categories"`
	FollowerCount    int32          `json:"follower_count"`
	TotalRaisedCents int64          `json:"total_raised_cents"`
	RafflesRun       int32          `json:"raffles_run"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	FollowedAt       time.Time      `json:"followed_at"`
	IsVerified       bool           `json:"is_verified"`
	ActiveRaffles    int32          `json:"active_raffles"`
}

func (q *Queries) ListFollowedOrgs(ctx context.Context, userID uuid.UUID) ([]ListFollowedOrgsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowedOrgs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowedOrgsRow{}
	for rows.Next() {
		var i ListFollowedOrgsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Image,
			&i.Address,
			&i.Phone,
			&i.Ein,
			&i.HasToPay,
			&i.Website,
			pq.Array(&i.Categories),
			&i.FollowerCount,
			&i.TotalRaisedCents,
			&i.RafflesRun,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FollowedAt,
			&i.IsVerified,
			&i.ActiveRaffles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowerIDsForOrg = `-- name: ListFollowerIDsForOrg :many
SELECT
    user_id
FROM
    org_follows
WHERE
    nonprofit_id = $1
`

// For "new raffle from followed org" notifications.
func (q *Queries) ListFollowerIDsForOrg(ctx context.Context, nonprofitID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listFollowerIDsForOrg, nonprofitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsForOrg = `-- name: ListReviewsForOrg :many
SELECT
    r.id, r.nonprofit_id, r.user_id, r.rating, r.body, r.created_at, r.updated_at,
    u.name AS user_name,
    u.image AS user_image
FROM
    nonprofit_reviews r
    JOIN users u ON u.id = r.user_id
WHERE
    r.nonprofit_id = $1
ORDER BY
    r.created_at DESC
LIMIT
    $3 OFFSET $2
`

type ListReviewsForOrgParams struct {
	NonprofitID  uuid.UUID `json:"nonprofit_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

type ListReviewsForOrgRow struct {
	ID          uuid.UUID      `json:"id"`
	NonprofitID uuid.UUID      `json:"nonprofit_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Rating      int32          `json:"rating"`
	Body        sql.NullString `json:"body"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UserName    string         `json:"user_name"`
	UserImage   sql.NullString `json:"user_image"`
}

// ── Reviews ───────────────────────────────────────────────────────────────────
func (q *Queries) ListReviewsForOrg(ctx context.Context, arg ListReviewsForOrgParams) ([]ListReviewsForOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsForOrg, arg.NonprofitID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsForOrgRow{}
	for rows.Next() {
		var i ListReviewsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.NonprofitID,
			&i.UserID,
			&i.Rating,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedRaffles = `-- name: ListSavedRaffles :many
SELECT
    ri.id, ri.category_id, ri.category_path, ri.title, ri.slug, ri.description, ri.status, ri.ticket_strategy, ri.ticket_assignment_strategy, ri.draw_strategy, ri.ticket_price, ri.free_tickets, ri.free_ticket_start_range, ri.free_ticket_end_range, ri.max_tickets, ri.tickets_sold, ri.attributes, ri.image_urls, ri.draw_at, ri.drawn_at, ri.created_by, ri.created_at, ri.updated_at,
    c.icon AS category_icon,
    n.name AS nonprofit_name,
    sr.created_at AS saved_at
FROM
    saved_raffles sr
    JOIN raffle_items ri ON ri.id = sr.raffle_item_id
    JOIN categories c ON c.id = ri.category_id
    LEFT JOIN nonprofits n ON n.id = ri.created_by
WHERE
    sr.user_id = $1
ORDER BY
    sr.created_at DESC
`

type ListSavedRafflesRow struct {
	ID                       uuid.UUID                `json:"id"`
	CategoryID               uuid.UUID                `json:"category_id"`
	CategoryPath             string                   `json:"category_path"`
	Title                    string                   `json:"title"`
	Slug                     sql.NullString           `json:"slug"`
	Description              sql.NullString           `json:"description"`
	Status                   RaffleItemStatus         `json:"status"`
	TicketStrategy           TicketStrategy           `json:"ticket_strategy"`
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	DrawStrategy             DrawStrategy             `json:"draw_strategy"`
	TicketPrice              sql.NullString           `json:"ticket_price"`
	FreeTickets              int32                    `json:"free_tickets"`
	FreeTicketStartRange     sql.NullInt32            `json:"free_ticket_start_range"`
	FreeTicketEndRange       sql.NullInt32            `json:"free_ticket_end_range"`
	MaxTickets               sql.NullInt32            `json:"max_tickets"`
	TicketsSold              int32                    `json:"tickets_sold"`
	Attributes               json.RawMessage          `json:"attributes"`
	ImageUrls                []string                 `json:"image_urls"`
	DrawAt                   sql.NullTime             `json:"draw_at"`
	DrawnAt                  sql.NullTime             `json:"drawn_at"`
	CreatedBy                uuid.NullUUID            `json:"created_by"`
	CreatedAt                time.Time                `json:"created_at"`
	UpdatedAt                time.Time                `json:"updated_at"`
	CategoryIcon             sql.NullString           `json:"category_icon"`
	NonprofitName            sql.NullString           `json:"nonprofit_name"`
	SavedAt                  time.Time                `json:"saved_at"`
}

func (q *Queries) ListSavedRaffles(ctx context.Context, userID uuid.UUID) ([]ListSavedRafflesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSavedRaffles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedRafflesRow{}
	for rows.Next() {
		var i ListSavedRafflesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryPath,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.TicketAssignmentStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.FreeTickets,
			&i.FreeTicketStartRange,
			&i.FreeTicketEndRange,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.DrawAt,
			&i.DrawnAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryIcon,
			&i.NonprofitName,
			&i.SavedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRaffle = `-- name: SaveRaffle :one
INSERT INTO
    saved_raffles (user_id, raffle_item_id)
VALUES
    ($1, $2) ON CONFLICT (user_id, raffle_item_id) DO NOTHING
RETURNING
    id, user_id, raffle_item_id, created_at
`

type SaveRaffleParams struct {
	UserID       uuid.UUID `json:"user_id"`
	RaffleItemID uuid.UUID `json:"raffle_item_id"`
}

// ── Saved raffles ─────────────────────────────────────────────────────────────
func (q *Queries) SaveRaffle(ctx context.Context, arg SaveRaffleParams) (SavedRaffle, error) {
	row := q.db.QueryRowContext(ctx, saveRaffle, arg.UserID, arg.RaffleItemID)
	var i SavedRaffle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RaffleItemID,
		&i.CreatedAt,
	)
	return i, err
}

const unfollowOrg = `-- name: UnfollowOrg :exec
DELETE FROM
    org_follows
WHERE
    user_id = $1
    AND nonprofit_id = $2
`

type UnfollowOrgParams struct {
	UserID      uuid.UUID `json:"user_id"`
	NonprofitID uuid.UUID `json:"nonprofit_id"`
}

func (q *Queries) UnfollowOrg(ctx context.Context, arg UnfollowOrgParams) error {
	_, err := q.db.ExecContext(ctx, unfollowOrg, arg.UserID, arg.NonprofitID)
	return err
}

const unsaveRaffle = `-- name: UnsaveRaffle :exec
DELETE FROM
    saved_raffles
WHERE
    user_id = $1
    AND raffle_item_id = $2
`

type UnsaveRaffleParams struct {
	UserID       uuid.UUID `json:"user_id"`
	RaffleItemID uuid.UUID `json:"raffle_item_id"`
}

func (q *Queries) UnsaveRaffle(ctx context.Context, arg UnsaveRaffleParams) error {
	_, err := q.db.ExecContext(ctx, unsaveRaffle, arg.UserID, arg.RaffleItemID)
	return err
}

const upsertReview = `-- name: UpsertReview :one
INSERT INTO
    nonprofit_reviews (nonprofit_id, user_id, rating, body)
VALUES
    ($1, $2, $3, $4) ON CONFLICT (nonprofit_id, user_id) DO
UPDATE
SET
    rating = EXCLUDED.rating,
    body = EXCLUDED.body
RETURNING
    id, nonprofit_id, user_id, rating, body, created_at, updated_at
`

type UpsertReviewParams struct {
	NonprofitID uuid.UUID      `json:"nonprofit_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Rating      int32          `json:"rating"`
	Body        sql.NullString `json:"body"`
}

func (q *Queries) UpsertReview(ctx context.Context, arg UpsertReviewParams) (NonprofitReview, error) {
	row := q.db.QueryRowContext(ctx, upsertReview,
		arg.NonprofitID,
		arg.UserID,
		arg.Rating,
		arg.Body,
	)
	var i NonprofitReview
	err := row.Scan(
		&i.ID,
		&i.NonprofitID,
		&i.UserID,
		&i.Rating,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
