// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countRaffleViews = `-- name: CountRaffleViews :one
SELECT
    COUNT(*)::INT AS count
FROM
    raffle_views
WHERE
    raffle_item_id = $1
`

func (q *Queries) CountRaffleViews(ctx context.Context, raffleItemID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countRaffleViews, raffleItemID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countSharesForRaffle = `-- name: CountSharesForRaffle :one
SELECT
    COUNT(*)::INT AS count
FROM
    shares
WHERE
    raffle_item_id = $1
`

func (q *Queries) CountSharesForRaffle(ctx context.Context, raffleItemID uuid.NullUUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countSharesForRaffle, raffleItemID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getShareByToken = `-- name: GetShareByToken :one
SELECT
    id, user_id, raffle_item_id, nonprofit_id, channel, share_token, created_at
FROM
    shares
WHERE
    share_token = $1
`

func (q *Queries) GetShareByToken(ctx context.Context, shareToken sql.NullString) (Share, error) {
	row := q.db.QueryRowContext(ctx, getShareByToken, shareToken)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RaffleItemID,
		&i.NonprofitID,
		&i.Channel,
		&i.ShareToken,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityForNonprofit = `-- name: ListActivityForNonprofit :many
SELECT
    id, actor_user_id, nonprofit_id, raffle_item_id, event_type, metadata, created_at
FROM
    activity_events
WHERE
    nonprofit_id = $1
ORDER BY
    created_at DESC
LIMIT
    $3 OFFSET $2
`

type ListActivityForNonprofitParams struct {
	NonprofitID  uuid.NullUUID `json:"nonprofit_id"`
	ResultOffset int32         `json:"result_offset"`
	ResultLimit  int32         `json:"result_limit"`
}

// Powers the dashboard recent-activity feed.
func (q *Queries) ListActivityForNonprofit(ctx context.Context, arg ListActivityForNonprofitParams) ([]ActivityEvent, error) {
	rows, err := q.db.QueryContext(ctx, listActivityForNonprofit, arg.NonprofitID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityEvent{}
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.NonprofitID,
			&i.RaffleItemID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordActivityEvent = `-- name: RecordActivityEvent :exec
INSERT INTO
    activity_events (
        actor_user_id,
        nonprofit_id,
        raffle_item_id,
        event_type,
        metadata
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5
    )
`

type RecordActivityEventParams struct {
	ActorUserID  uuid.NullUUID   `json:"actor_user_id"`
	NonprofitID  uuid.NullUUID   `json:"nonprofit_id"`
	RaffleItemID uuid.NullUUID   `json:"raffle_item_id"`
	EventType    string          `json:"event_type"`
	Metadata     json.RawMessage `json:"metadata"`
}

// ── Activity events (dashboard feed) ──────────────────────────────────────────
func (q *Queries) RecordActivityEvent(ctx context.Context, arg RecordActivityEventParams) error {
	_, err := q.db.ExecContext(ctx, recordActivityEvent,
		arg.ActorUserID,
		arg.NonprofitID,
		arg.RaffleItemID,
		arg.EventType,
		arg.Metadata,
	)
	return err
}

const recordRaffleView = `-- name: RecordRaffleView :exec
INSERT INTO raffle_views (raffle_item_id)
VALUES ($1::uuid)
`

// ── Raffle views ──────────────────────────────────────────────────────────────
// Records one raffle view for conversion analytics. Called (fire-and-forget)
// from the public GET /raffles/{id} handler. Anonymous views are fine.
// NOTE: if raffle_views has a nullable user_id column you want to populate,
// add `, user_id` here and `, sqlc.narg(user_id)` to VALUES.
func (q *Queries) RecordRaffleView(ctx context.Context, raffleItemID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, recordRaffleView, raffleItemID)
	return err
}

const recordSearch = `-- name: RecordSearch :exec
INSERT INTO
    search_events (user_id, query, result_count, clicked_raffle_id)
VALUES
    (
        $1,
        $2,
        $3,
        $4
    )
`

type RecordSearchParams struct {
	UserID          uuid.NullUUID `json:"user_id"`
	Query           string        `json:"query"`
	ResultCount     int32         `json:"result_count"`
	ClickedRaffleID uuid.NullUUID `json:"clicked_raffle_id"`
}

// ── Search events ─────────────────────────────────────────────────────────────
func (q *Queries) RecordSearch(ctx context.Context, arg RecordSearchParams) error {
	_, err := q.db.ExecContext(ctx, recordSearch,
		arg.UserID,
		arg.Query,
		arg.ResultCount,
		arg.ClickedRaffleID,
	)
	return err
}

const recordShare = `-- name: RecordShare :one
INSERT INTO
    shares (
        user_id,
        raffle_item_id,
        nonprofit_id,
        channel,
        share_token
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5
    )
RETURNING
    id, user_id, raffle_item_id, nonprofit_id, channel, share_token, created_at
`

type RecordShareParams struct {
	UserID       uuid.NullUUID  `json:"user_id"`
	RaffleItemID uuid.NullUUID  `json:"raffle_item_id"`
	NonprofitID  uuid.NullUUID  `json:"nonprofit_id"`
	Channel      sql.NullString `json:"channel"`
	ShareToken   sql.NullString `json:"share_token"`
}

// ── Shares ────────────────────────────────────────────────────────────────────
func (q *Queries) RecordShare(ctx context.Context, arg RecordShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, recordShare,
		arg.UserID,
		arg.RaffleItemID,
		arg.NonprofitID,
		arg.Channel,
		arg.ShareToken,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RaffleItemID,
		&i.NonprofitID,
		&i.Channel,
		&i.ShareToken,
		&i.CreatedAt,
	)
	return i, err
}

const topSearchQueries = `-- name: TopSearchQueries :many
SELECT
    query,
    COUNT(*)::INT AS count
FROM
    search_events
WHERE
    created_at >= $1
GROUP BY
    query
ORDER BY
    count DESC
LIMIT
    $2
`

type TopSearchQueriesParams struct {
	WindowStart time.Time `json:"window_start"`
	ResultLimit int32     `json:"result_limit"`
}

type TopSearchQueriesRow struct {
	Query string `json:"query"`
	Count int32  `json:"count"`
}

// Demand sensing: most common searches over a window.
func (q *Queries) TopSearchQueries(ctx context.Context, arg TopSearchQueriesParams) ([]TopSearchQueriesRow, error) {
	rows, err := q.db.QueryContext(ctx, topSearchQueries, arg.WindowStart, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopSearchQueriesRow{}
	for rows.Next() {
		var i TopSearchQueriesRow
		if err := rows.Scan(&i.Query, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topZeroResultSearches = `-- name: TopZeroResultSearches :many
SELECT
    query,
    COUNT(*)::INT AS count
FROM
    search_events
WHERE
    result_count = 0
    AND created_at >= $1
GROUP BY
    query
ORDER BY
    count DESC
LIMIT
    $2
`

type TopZeroResultSearchesParams struct {
	WindowStart time.Time `json:"window_start"`
	ResultLimit int32     `json:"result_limit"`
}

type TopZeroResultSearchesRow struct {
	Query string `json:"query"`
	Count int32  `json:"count"`
}

// Searches that returned nothing — prizes people want that you don't have.
func (q *Queries) TopZeroResultSearches(ctx context.Context, arg TopZeroResultSearchesParams) ([]TopZeroResultSearchesRow, error) {
	rows, err := q.db.QueryContext(ctx, topZeroResultSearches, arg.WindowStart, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopZeroResultSearchesRow{}
	for rows.Next() {
		var i TopZeroResultSearchesRow
		if err := rows.Scan(&i.Query, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
