// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type DrawStrategy string

const (
	DrawStrategySingle        DrawStrategy = "single"
	DrawStrategyRanked        DrawStrategy = "ranked"
	DrawStrategyMultipleEqual DrawStrategy = "multiple_equal"
	DrawStrategyCountdown     DrawStrategy = "countdown"
)

func (e *DrawStrategy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DrawStrategy(s)
	case string:
		*e = DrawStrategy(s)
	default:
		return fmt.Errorf("unsupported scan type for DrawStrategy: %T", src)
	}
	return nil
}

type NullDrawStrategy struct {
	DrawStrategy DrawStrategy `json:"draw_strategy"`
	Valid        bool         `json:"valid"` // Valid is true if DrawStrategy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDrawStrategy) Scan(value interface{}) error {
	if value == nil {
		ns.DrawStrategy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DrawStrategy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDrawStrategy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DrawStrategy), nil
}

type RaffleItemStatus string

const (
	RaffleItemStatusDraft     RaffleItemStatus = "draft"
	RaffleItemStatusActive    RaffleItemStatus = "active"
	RaffleItemStatusClosed    RaffleItemStatus = "closed"
	RaffleItemStatusDrawing   RaffleItemStatus = "drawing"
	RaffleItemStatusCompleted RaffleItemStatus = "completed"
	RaffleItemStatusCancelled RaffleItemStatus = "cancelled"
)

func (e *RaffleItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RaffleItemStatus(s)
	case string:
		*e = RaffleItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RaffleItemStatus: %T", src)
	}
	return nil
}

type NullRaffleItemStatus struct {
	RaffleItemStatus RaffleItemStatus `json:"raffle_item_status"`
	Valid            bool             `json:"valid"` // Valid is true if RaffleItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRaffleItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RaffleItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RaffleItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRaffleItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RaffleItemStatus), nil
}

type TicketAssignmentStrategy string

const (
	TicketAssignmentStrategyRandom    TicketAssignmentStrategy = "random"
	TicketAssignmentStrategyUserPicks TicketAssignmentStrategy = "user_picks"
)

func (e *TicketAssignmentStrategy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketAssignmentStrategy(s)
	case string:
		*e = TicketAssignmentStrategy(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketAssignmentStrategy: %T", src)
	}
	return nil
}

type NullTicketAssignmentStrategy struct {
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	Valid                    bool                     `json:"valid"` // Valid is true if TicketAssignmentStrategy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketAssignmentStrategy) Scan(value interface{}) error {
	if value == nil {
		ns.TicketAssignmentStrategy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketAssignmentStrategy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketAssignmentStrategy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketAssignmentStrategy), nil
}

type TicketStrategy string

const (
	TicketStrategyFixed          TicketStrategy = "fixed"
	TicketStrategyBundle         TicketStrategy = "bundle"
	TicketStrategyDonation       TicketStrategy = "donation"
	TicketStrategyFree           TicketStrategy = "free"
	TicketStrategyPayWhatYouPull TicketStrategy = "pay_what_you_pull"
)

func (e *TicketStrategy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStrategy(s)
	case string:
		*e = TicketStrategy(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStrategy: %T", src)
	}
	return nil
}

type NullTicketStrategy struct {
	TicketStrategy TicketStrategy `json:"ticket_strategy"`
	Valid          bool           `json:"valid"` // Valid is true if TicketStrategy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStrategy) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStrategy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStrategy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStrategy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStrategy), nil
}

type Account struct {
	ID                    uuid.UUID      `json:"id"`
	AccountId             string         `json:"accountId"`
	ProviderId            string         `json:"providerId"`
	UserId                uuid.UUID      `json:"userId"`
	AccessToken           sql.NullString `json:"accessToken"`
	RefreshToken          sql.NullString `json:"refreshToken"`
	IdToken               sql.NullString `json:"idToken"`
	AccessTokenExpiresAt  sql.NullTime   `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt sql.NullTime   `json:"refreshTokenExpiresAt"`
	Scope                 sql.NullString `json:"scope"`
	Password              sql.NullString `json:"password"`
	CreatedAt             time.Time      `json:"createdAt"`
	UpdatedAt             time.Time      `json:"updatedAt"`
}

type ActivityEvent struct {
	ID           int64           `json:"id"`
	ActorUserID  uuid.NullUUID   `json:"actor_user_id"`
	NonprofitID  uuid.NullUUID   `json:"nonprofit_id"`
	RaffleItemID uuid.NullUUID   `json:"raffle_item_id"`
	EventType    string          `json:"event_type"`
	Metadata     json.RawMessage `json:"metadata"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Category struct {
	ID              uuid.UUID             `json:"id"`
	ParentID        uuid.NullUUID         `json:"parent_id"`
	Path            string                `json:"path"`
	Depth           int32                 `json:"depth"`
	Name            string                `json:"name"`
	Slug            string                `json:"slug"`
	Icon            sql.NullString        `json:"icon"`
	SortOrder       int32                 `json:"sort_order"`
	AttributeSchema pqtype.NullRawMessage `json:"attribute_schema"`
	IsActive        bool                  `json:"is_active"`
	CreatedAt       time.Time             `json:"created_at"`
	UpdatedAt       time.Time             `json:"updated_at"`
}

type DrawResult struct {
	ID                uuid.UUID      `json:"id"`
	RaffleItemID      uuid.UUID      `json:"raffle_item_id"`
	DrawStrategy      DrawStrategy   `json:"draw_strategy"`
	RevealOrder       string         `json:"reveal_order"`
	WinnerCount       int32          `json:"winner_count"`
	CommitmentHash    string         `json:"commitment_hash"`
	Seed              sql.NullString `json:"seed"`
	DrawStartedAt     sql.NullTime   `json:"draw_started_at"`
	DrawDurationMs    int32          `json:"draw_duration_ms"`
	TotalTickets      int32          `json:"total_tickets"`
	TotalParticipants int32          `json:"total_participants"`
	VerificationUrl   sql.NullString `json:"verification_url"`
	Status            string         `json:"status"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type DrawWinner struct {
	ID               uuid.UUID      `json:"id"`
	DrawResultID     uuid.UUID      `json:"draw_result_id"`
	PullIndex        int32          `json:"pull_index"`
	Rank             int32          `json:"rank"`
	TicketID         uuid.UUID      `json:"ticket_id"`
	TicketNumber     int32          `json:"ticket_number"`
	UserID           uuid.UUID      `json:"user_id"`
	PrizeTitle       string         `json:"prize_title"`
	PrizeDescription sql.NullString `json:"prize_description"`
	PrizeValueCents  sql.NullInt32  `json:"prize_value_cents"`
	RevealedAtMs     int32          `json:"revealed_at_ms"`
	PrizeClaimed     bool           `json:"prize_claimed"`
	ClaimedAt        sql.NullTime   `json:"claimed_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Nonprofit struct {
	ID               uuid.UUID      `json:"id"`
	Name             string         `json:"name"`
	Slug             sql.NullString `json:"slug"`
	Description      sql.NullString `json:"description"`
	Image            sql.NullString `json:"image"`
	Address          sql.NullString `json:"address"`
	Phone            sql.NullString `json:"phone"`
	Ein              sql.NullString `json:"ein"`
	HasToPay         bool           `json:"hasToPay"`
	Website          sql.NullString `json:"website"`
	Categories       []string       `json:"categories"`
	FollowerCount    int32          `json:"follower_count"`
	TotalRaisedCents int64          `json:"total_raised_cents"`
	RafflesRun       int32          `json:"raffles_run"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type NonprofitBankAccount struct {
	ID                 uuid.UUID      `json:"id"`
	NonprofitID        uuid.UUID      `json:"nonprofit_id"`
	Processor          string         `json:"processor"`
	ProcessorAccountID string         `json:"processor_account_id"`
	BankName           sql.NullString `json:"bank_name"`
	Last4              sql.NullString `json:"last4"`
	AccountType        sql.NullString `json:"account_type"`
	IsVerified         bool           `json:"is_verified"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type NonprofitReview struct {
	ID          uuid.UUID      `json:"id"`
	NonprofitID uuid.UUID      `json:"nonprofit_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Rating      int32          `json:"rating"`
	Body        sql.NullString `json:"body"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type NonprofitSocialLink struct {
	ID          uuid.UUID `json:"id"`
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	Platform    string    `json:"platform"`
	Url         string    `json:"url"`
}

type NonprofitUser struct {
	ID          uuid.UUID `json:"id"`
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	Mode        string    `json:"mode"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type NonprofitVerification struct {
	ID                 uuid.UUID      `json:"id"`
	NonprofitID        uuid.UUID      `json:"nonprofit_id"`
	IsVerified         sql.NullBool   `json:"isVerified"`
	VerificationMethod sql.NullString `json:"verificationMethod"`
	ExemptStatus       sql.NullInt32  `json:"exemptStatus"`
	Subsection         sql.NullInt32  `json:"subsection"`
	NteeCd             sql.NullString `json:"nteeCd"`
	RulingDate         sql.NullTime   `json:"rulingDate"`
	UpdatedAt          time.Time      `json:"updated_at"`
	CreatedAt          time.Time      `json:"created_at"`
	Foundation         sql.NullInt32  `json:"foundation"`
}

type NotificationPreference struct {
	ID          uuid.UUID       `json:"id"`
	UserID      uuid.NullUUID   `json:"user_id"`
	NonprofitID uuid.NullUUID   `json:"nonprofit_id"`
	Prefs       json.RawMessage `json:"prefs"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Order struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.UUID      `json:"user_id"`
	RaffleItemID       uuid.UUID      `json:"raffle_item_id"`
	TicketCount        int32          `json:"ticket_count"`
	SubtotalCents      int32          `json:"subtotal_cents"`
	DonationCents      int32          `json:"donation_cents"`
	TotalCents         int32          `json:"total_cents"`
	Processor          string         `json:"processor"`
	ProcessorPaymentID sql.NullString `json:"processor_payment_id"`
	Status             string         `json:"status"`
	ReceiptNumber      sql.NullString `json:"receipt_number"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type OrgFollow struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type PaymentMethod struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	Processor     string    `json:"processor"`
	ProcessorPmID string    `json:"processor_pm_id"`
	Brand         string    `json:"brand"`
	Last4         string    `json:"last4"`
	ExpMonth      int32     `json:"exp_month"`
	ExpYear       int32     `json:"exp_year"`
	IsDefault     bool      `json:"is_default"`
	CreatedAt     time.Time `json:"created_at"`
}

type Payout struct {
	ID                uuid.UUID      `json:"id"`
	NonprofitID       uuid.UUID      `json:"nonprofit_id"`
	RaffleItemID      uuid.NullUUID  `json:"raffle_item_id"`
	AmountCents       int32          `json:"amount_cents"`
	Status            string         `json:"status"`
	ProcessorPayoutID sql.NullString `json:"processor_payout_id"`
	CreatedAt         time.Time      `json:"created_at"`
	PaidAt            sql.NullTime   `json:"paid_at"`
}

type PrizeTier struct {
	ID           uuid.UUID      `json:"id"`
	RaffleItemID uuid.UUID      `json:"raffle_item_id"`
	Rank         int32          `json:"rank"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	ValueCents   sql.NullInt32  `json:"value_cents"`
	ImageUrl     sql.NullString `json:"image_url"`
}

type RaffleItem struct {
	ID                       uuid.UUID                `json:"id"`
	CategoryID               uuid.UUID                `json:"category_id"`
	CategoryPath             string                   `json:"category_path"`
	Title                    string                   `json:"title"`
	Slug                     sql.NullString           `json:"slug"`
	Description              sql.NullString           `json:"description"`
	Status                   RaffleItemStatus         `json:"status"`
	TicketStrategy           TicketStrategy           `json:"ticket_strategy"`
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	DrawStrategy             DrawStrategy             `json:"draw_strategy"`
	TicketPrice              sql.NullString           `json:"ticket_price"`
	FreeTickets              int32                    `json:"free_tickets"`
	FreeTicketStartRange     sql.NullInt32            `json:"free_ticket_start_range"`
	FreeTicketEndRange       sql.NullInt32            `json:"free_ticket_end_range"`
	MaxTickets               sql.NullInt32            `json:"max_tickets"`
	TicketsSold              int32                    `json:"tickets_sold"`
	Attributes               json.RawMessage          `json:"attributes"`
	ImageUrls                []string                 `json:"image_urls"`
	DrawAt                   sql.NullTime             `json:"draw_at"`
	DrawnAt                  sql.NullTime             `json:"drawn_at"`
	CreatedBy                uuid.NullUUID            `json:"created_by"`
	CreatedAt                time.Time                `json:"created_at"`
	UpdatedAt                time.Time                `json:"updated_at"`
}

type RaffleView struct {
	ID           int64          `json:"id"`
	RaffleItemID uuid.UUID      `json:"raffle_item_id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	SessionID    sql.NullString `json:"session_id"`
	Source       sql.NullString `json:"source"`
	Referrer     sql.NullString `json:"referrer"`
	CreatedAt    time.Time      `json:"created_at"`
}

type SavedRaffle struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RaffleItemID uuid.UUID `json:"raffle_item_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type SearchEvent struct {
	ID              int64         `json:"id"`
	UserID          uuid.NullUUID `json:"user_id"`
	Query           string        `json:"query"`
	ResultCount     int32         `json:"result_count"`
	ClickedRaffleID uuid.NullUUID `json:"clicked_raffle_id"`
	CreatedAt       time.Time     `json:"created_at"`
}

type Session struct {
	ID        uuid.UUID      `json:"id"`
	ExpiresAt time.Time      `json:"expiresAt"`
	Token     string         `json:"token"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	IpAddress sql.NullString `json:"ipAddress"`
	UserAgent sql.NullString `json:"userAgent"`
	UserId    uuid.UUID      `json:"userId"`
}

type Share struct {
	ID           int64          `json:"id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	RaffleItemID uuid.NullUUID  `json:"raffle_item_id"`
	NonprofitID  uuid.NullUUID  `json:"nonprofit_id"`
	Channel      sql.NullString `json:"channel"`
	ShareToken   sql.NullString `json:"share_token"`
	CreatedAt    time.Time      `json:"created_at"`
}

type ShippingAddress struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	Line1     string         `json:"line1"`
	Line2     sql.NullString `json:"line2"`
	City      string         `json:"city"`
	State     string         `json:"state"`
	Zip       string         `json:"zip"`
	Country   string         `json:"country"`
	IsDefault bool           `json:"is_default"`
	CreatedAt time.Time      `json:"created_at"`
}

type Ticket struct {
	ID           uuid.UUID     `json:"id"`
	RaffleItemID uuid.UUID     `json:"raffle_item_id"`
	UserID       uuid.UUID     `json:"user_id"`
	OrderID      uuid.NullUUID `json:"order_id"`
	TicketNumber int32         `json:"ticket_number"`
	PricePaid    string        `json:"price_paid"`
	PurchasedAt  time.Time     `json:"purchased_at"`
}

type User struct {
	ID                  uuid.UUID      `json:"id"`
	Name                string         `json:"name"`
	Email               string         `json:"email"`
	EmailVerified       bool           `json:"emailVerified"`
	Image               sql.NullString `json:"image"`
	CreatedAt           time.Time      `json:"createdAt"`
	UpdatedAt           time.Time      `json:"updatedAt"`
	PreferredCategories []string       `json:"preferred_categories"`
	LocationRegion      sql.NullString `json:"location_region"`
}

type VActiveRaffle struct {
	ID             uuid.UUID        `json:"id"`
	Title          string           `json:"title"`
	Slug           sql.NullString   `json:"slug"`
	Description    sql.NullString   `json:"description"`
	Status         RaffleItemStatus `json:"status"`
	TicketStrategy TicketStrategy   `json:"ticket_strategy"`
	DrawStrategy   DrawStrategy     `json:"draw_strategy"`
	TicketPrice    sql.NullString   `json:"ticket_price"`
	MaxTickets     sql.NullInt32    `json:"max_tickets"`
	TicketsSold    int32            `json:"tickets_sold"`
	DrawAt         sql.NullTime     `json:"draw_at"`
	CreatedAt      time.Time        `json:"created_at"`
	Attributes     json.RawMessage  `json:"attributes"`
	ImageUrls      []string         `json:"image_urls"`
	CategoryPath   string           `json:"category_path"`
	NonprofitID    uuid.NullUUID    `json:"nonprofit_id"`
	CategoryID     uuid.UUID        `json:"category_id"`
	CategoryName   string           `json:"category_name"`
	CategorySlug   string           `json:"category_slug"`
	CategoryIcon   sql.NullString   `json:"category_icon"`
	CategoryDepth  int32            `json:"category_depth"`
	NonprofitName  sql.NullString   `json:"nonprofit_name"`
}

type VCategoryItemCount struct {
	ID              uuid.UUID             `json:"id"`
	Name            string                `json:"name"`
	Slug            string                `json:"slug"`
	Path            string                `json:"path"`
	ParentID        uuid.NullUUID         `json:"parent_id"`
	Depth           int32                 `json:"depth"`
	Icon            sql.NullString        `json:"icon"`
	SortOrder       int32                 `json:"sort_order"`
	AttributeSchema pqtype.NullRawMessage `json:"attribute_schema"`
	ActiveItemCount int64                 `json:"active_item_count"`
}

type Verification struct {
	ID         uuid.UUID `json:"id"`
	Identifier string    `json:"identifier"`
	Value      string    `json:"value"`
	ExpiresAt  time.Time `json:"expiresAt"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}
