// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nonprofits.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO
    nonprofit_users (nonprofit_id, user_id, role, MODE)
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, nonprofit_id, user_id, role, mode, created_at, updated_at
`

type AddTeamMemberParams struct {
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	Mode        string    `json:"mode"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (NonprofitUser, error) {
	row := q.db.QueryRowContext(ctx, addTeamMember,
		arg.NonprofitID,
		arg.UserID,
		arg.Role,
		arg.Mode,
	)
	var i NonprofitUser
	err := row.Scan(
		&i.ID,
		&i.NonprofitID,
		&i.UserID,
		&i.Role,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNonprofit = `-- name: CreateNonprofit :one
INSERT INTO
    nonprofits (
        name,
        slug,
        description,
        image,
        address,
        phone,
        ein,
        "hasToPay",
        website,
        categories
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id, name, slug, description, image, address, phone, ein, "hasToPay", website, categories, follower_count, total_raised_cents, raffles_run, created_at, updated_at
`

type CreateNonprofitParams struct {
	Name        string         `json:"name"`
	Slug        sql.NullString `json:"slug"`
	Description sql.NullString `json:"description"`
	Image       sql.NullString `json:"image"`
	Address     sql.NullString `json:"address"`
	Phone       sql.NullString `json:"phone"`
	Ein         sql.NullString `json:"ein"`
	HasToPay    bool           `json:"hasToPay"`
	Website     sql.NullString `json:"website"`
	Categories  []string       `json:"categories"`
}

func (q *Queries) CreateNonprofit(ctx context.Context, arg CreateNonprofitParams) (Nonprofit, error) {
	row := q.db.QueryRowContext(ctx, createNonprofit,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Image,
		arg.Address,
		arg.Phone,
		arg.Ein,
		arg.HasToPay,
		arg.Website,
		pq.Array(arg.Categories),
	)
	var i Nonprofit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Address,
		&i.Phone,
		&i.Ein,
		&i.HasToPay,
		&i.Website,
		pq.Array(&i.Categories),
		&i.FollowerCount,
		&i.TotalRaisedCents,
		&i.RafflesRun,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayout = `-- name: CreatePayout :one
INSERT INTO
    payouts (
        nonprofit_id,
        raffle_item_id,
        amount_cents,
        STATUS,
        processor_payout_id
    )
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id, nonprofit_id, raffle_item_id, amount_cents, status, processor_payout_id, created_at, paid_at
`

type CreatePayoutParams struct {
	NonprofitID       uuid.UUID      `json:"nonprofit_id"`
	RaffleItemID      uuid.NullUUID  `json:"raffle_item_id"`
	AmountCents       int32          `json:"amount_cents"`
	Status            string         `json:"status"`
	ProcessorPayoutID sql.NullString `json:"processor_payout_id"`
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRowContext(ctx, createPayout,
		arg.NonprofitID,
		arg.RaffleItemID,
		arg.AmountCents,
		arg.Status,
		arg.ProcessorPayoutID,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.NonprofitID,
		&i.RaffleItemID,
		&i.AmountCents,
		&i.Status,
		&i.ProcessorPayoutID,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const deleteSocialLinks = `-- name: DeleteSocialLinks :exec
DELETE FROM
    nonprofit_social_links
WHERE
    nonprofit_id = $1
`

func (q *Queries) DeleteSocialLinks(ctx context.Context, nonprofitID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSocialLinks, nonprofitID)
	return err
}

const getBankAccount = `-- name: GetBankAccount :one
SELECT
    id, nonprofit_id, processor, processor_account_id, bank_name, last4, account_type, is_verified, created_at, updated_at
FROM
    nonprofit_bank_accounts
WHERE
    nonprofit_id = $1
ORDER BY
    created_at DESC
LIMIT
    1
`

// ── Bank account & payouts ───────────────────────────────────────────────────
func (q *Queries) GetBankAccount(ctx context.Context, nonprofitID uuid.UUID) (NonprofitBankAccount, error) {
	row := q.db.QueryRowContext(ctx, getBankAccount, nonprofitID)
	var i NonprofitBankAccount
	err := row.Scan(
		&i.ID,
		&i.NonprofitID,
		&i.Processor,
		&i.ProcessorAccountID,
		&i.BankName,
		&i.Last4,
		&i.AccountType,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNonprofitAllTimeStats = `-- name: GetNonprofitAllTimeStats :one
SELECT
    n.id AS org_id,
    n.name AS org_name,
    n.total_raised_cents,
    n.raffles_run,
    n.follower_count,
    COALESCE(
        (
            SELECT
                COUNT(*)
            FROM
                tickets t
                JOIN raffle_items ri ON ri.id = t.raffle_item_id
            WHERE
                ri.created_by = n.id
        ),
        0
    ) AS total_tickets_sold
FROM
    nonprofits n
WHERE
    n.id = $1
`

type GetNonprofitAllTimeStatsRow struct {
	OrgID            uuid.UUID   `json:"org_id"`
	OrgName          string      `json:"org_name"`
	TotalRaisedCents int64       `json:"total_raised_cents"`
	RafflesRun       int32       `json:"raffles_run"`
	FollowerCount    int32       `json:"follower_count"`
	TotalTicketsSold interface{} `json:"total_tickets_sold"`
}

// ── Dashboard / Org all-time stats ────────────────────────────────────────────
func (q *Queries) GetNonprofitAllTimeStats(ctx context.Context, id uuid.UUID) (GetNonprofitAllTimeStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getNonprofitAllTimeStats, id)
	var i GetNonprofitAllTimeStatsRow
	err := row.Scan(
		&i.OrgID,
		&i.OrgName,
		&i.TotalRaisedCents,
		&i.RafflesRun,
		&i.FollowerCount,
		&i.TotalTicketsSold,
	)
	return i, err
}

const getNonprofitByID = `-- name: GetNonprofitByID :one
SELECT
    id, name, slug, description, image, address, phone, ein, "hasToPay", website, categories, follower_count, total_raised_cents, raffles_run, created_at, updated_at
FROM
    nonprofits
WHERE
    id = $1
`

func (q *Queries) GetNonprofitByID(ctx context.Context, id uuid.UUID) (Nonprofit, error) {
	row := q.db.QueryRowContext(ctx, getNonprofitByID, id)
	var i Nonprofit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Address,
		&i.Phone,
		&i.Ein,
		&i.HasToPay,
		&i.Website,
		pq.Array(&i.Categories),
		&i.FollowerCount,
		&i.TotalRaisedCents,
		&i.RafflesRun,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNonprofitBySlug = `-- name: GetNonprofitBySlug :one
SELECT
    id, name, slug, description, image, address, phone, ein, "hasToPay", website, categories, follower_count, total_raised_cents, raffles_run, created_at, updated_at
FROM
    nonprofits
WHERE
    slug = $1
`

func (q *Queries) GetNonprofitBySlug(ctx context.Context, slug sql.NullString) (Nonprofit, error) {
	row := q.db.QueryRowContext(ctx, getNonprofitBySlug, slug)
	var i Nonprofit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Address,
		&i.Phone,
		&i.Ein,
		&i.HasToPay,
		&i.Website,
		pq.Array(&i.Categories),
		&i.FollowerCount,
		&i.TotalRaisedCents,
		&i.RafflesRun,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNonprofitForUser = `-- name: GetNonprofitForUser :one
SELECT
    n.id, n.name, n.slug, n.description, n.image, n.address, n.phone, n.ein, n."hasToPay", n.website, n.categories, n.follower_count, n.total_raised_cents, n.raffles_run, n.created_at, n.updated_at
FROM
    nonprofits n
    JOIN nonprofit_users nu ON nu.nonprofit_id = n.id
WHERE
    nu.user_id = $1
LIMIT
    1
`

// The nonprofit a user manages (via membership).
func (q *Queries) GetNonprofitForUser(ctx context.Context, userID uuid.UUID) (Nonprofit, error) {
	row := q.db.QueryRowContext(ctx, getNonprofitForUser, userID)
	var i Nonprofit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Address,
		&i.Phone,
		&i.Ein,
		&i.HasToPay,
		&i.Website,
		pq.Array(&i.Categories),
		&i.FollowerCount,
		&i.TotalRaisedCents,
		&i.RafflesRun,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNonprofitMonthStats = `-- name: GetNonprofitMonthStats :one
SELECT
    COALESCE(SUM(t.price_paid), 0)::NUMERIC AS raised,
    COUNT(*)::INT AS tickets_sold
FROM
    tickets t
    JOIN raffle_items ri ON ri.id = t.raffle_item_id
WHERE
    ri.created_by = $1
    AND t.purchased_at >= $2
    AND t.purchased_at < $3
`

type GetNonprofitMonthStatsParams struct {
	NonprofitID uuid.NullUUID `json:"nonprofit_id"`
	WindowStart time.Time     `json:"window_start"`
	WindowEnd   time.Time     `json:"window_end"`
}

type GetNonprofitMonthStatsRow struct {
	Raised      string `json:"raised"`
	TicketsSold int32  `json:"tickets_sold"`
}

// Raised + tickets in a [window_start, window_end) range.
func (q *Queries) GetNonprofitMonthStats(ctx context.Context, arg GetNonprofitMonthStatsParams) (GetNonprofitMonthStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getNonprofitMonthStats, arg.NonprofitID, arg.WindowStart, arg.WindowEnd)
	var i GetNonprofitMonthStatsRow
	err := row.Scan(&i.Raised, &i.TicketsSold)
	return i, err
}

const getNonprofitVerification = `-- name: GetNonprofitVerification :one
SELECT
    id, nonprofit_id, "isVerified", "verificationMethod", "exemptStatus", subsection, "nteeCd", "rulingDate", updated_at, created_at, foundation
FROM
    nonprofit_verifications
WHERE
    nonprofit_id = $1
ORDER BY
    created_at DESC
LIMIT
    1
`

func (q *Queries) GetNonprofitVerification(ctx context.Context, nonprofitID uuid.UUID) (NonprofitVerification, error) {
	row := q.db.QueryRowContext(ctx, getNonprofitVerification, nonprofitID)
	var i NonprofitVerification
	err := row.Scan(
		&i.ID,
		&i.NonprofitID,
		&i.IsVerified,
		&i.VerificationMethod,
		&i.ExemptStatus,
		&i.Subsection,
		&i.NteeCd,
		&i.RulingDate,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Foundation,
	)
	return i, err
}

const getTicketsSoldSince = `-- name: GetTicketsSoldSince :one
SELECT
    COUNT(*)::INT AS count
FROM
    tickets t
    JOIN raffle_items ri ON ri.id = t.raffle_item_id
WHERE
    ri.created_by = $1
    AND t.purchased_at >= $2
`

type GetTicketsSoldSinceParams struct {
	NonprofitID uuid.NullUUID `json:"nonprofit_id"`
	Since       time.Time     `json:"since"`
}

// For "tickets today" / "tickets in last hour" dashboard metrics.
func (q *Queries) GetTicketsSoldSince(ctx context.Context, arg GetTicketsSoldSinceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getTicketsSoldSince, arg.NonprofitID, arg.Since)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getUserRoleInNonprofit = `-- name: GetUserRoleInNonprofit :one
SELECT
    role
FROM
    nonprofit_users
WHERE
    nonprofit_id = $1
    AND user_id = $2
`

type GetUserRoleInNonprofitParams struct {
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserRoleInNonprofit(ctx context.Context, arg GetUserRoleInNonprofitParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleInNonprofit, arg.NonprofitID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listNonprofitTeam = `-- name: ListNonprofitTeam :many
SELECT
    nu.id, nu.nonprofit_id, nu.user_id, nu.role, nu.mode, nu.created_at, nu.updated_at,
    u.name AS user_name,
    u.email AS user_email
FROM
    nonprofit_users nu
    JOIN users u ON u.id = nu.user_id
WHERE
    nu.nonprofit_id = $1
ORDER BY
    nu.created_at
`

type ListNonprofitTeamRow struct {
	ID          uuid.UUID `json:"id"`
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	Mode        string    `json:"mode"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	UserName    string    `json:"user_name"`
	UserEmail   string    `json:"user_email"`
}

// ── Team members ───────────────────────────────────────────────────────────────
func (q *Queries) ListNonprofitTeam(ctx context.Context, nonprofitID uuid.UUID) ([]ListNonprofitTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listNonprofitTeam, nonprofitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNonprofitTeamRow{}
	for rows.Next() {
		var i ListNonprofitTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.NonprofitID,
			&i.UserID,
			&i.Role,
			&i.Mode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayouts = `-- name: ListPayouts :many
SELECT
    id, nonprofit_id, raffle_item_id, amount_cents, status, processor_payout_id, created_at, paid_at
FROM
    payouts
WHERE
    nonprofit_id = $1
ORDER BY
    created_at DESC
LIMIT
    $3 OFFSET $2
`

type ListPayoutsParams struct {
	NonprofitID  uuid.UUID `json:"nonprofit_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

func (q *Queries) ListPayouts(ctx context.Context, arg ListPayoutsParams) ([]Payout, error) {
	rows, err := q.db.QueryContext(ctx, listPayouts, arg.NonprofitID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payout{}
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.NonprofitID,
			&i.RaffleItemID,
			&i.AmountCents,
			&i.Status,
			&i.ProcessorPayoutID,
			&i.CreatedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialLinks = `-- name: ListSocialLinks :many
SELECT
    id, nonprofit_id, platform, url
FROM
    nonprofit_social_links
WHERE
    nonprofit_id = $1
`

// ── Social links ─────────────────────────────────────────────────────────────
func (q *Queries) ListSocialLinks(ctx context.Context, nonprofitID uuid.UUID) ([]NonprofitSocialLink, error) {
	rows, err := q.db.QueryContext(ctx, listSocialLinks, nonprofitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NonprofitSocialLink{}
	for rows.Next() {
		var i NonprofitSocialLink
		if err := rows.Scan(
			&i.ID,
			&i.NonprofitID,
			&i.Platform,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPayoutPaid = `-- name: MarkPayoutPaid :exec
UPDATE
    payouts
SET
    STATUS = 'paid',
    paid_at = NOW()
WHERE
    id = $1
`

func (q *Queries) MarkPayoutPaid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markPayoutPaid, id)
	return err
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM
    nonprofit_users
WHERE
    nonprofit_id = $1
    AND user_id = $2
`

type RemoveTeamMemberParams struct {
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.NonprofitID, arg.UserID)
	return err
}

const replaceSocialLink = `-- name: ReplaceSocialLink :one
INSERT INTO
    nonprofit_social_links (nonprofit_id, platform, url)
VALUES
    ($1, $2, $3)
RETURNING
    id, nonprofit_id, platform, url
`

type ReplaceSocialLinkParams struct {
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	Platform    string    `json:"platform"`
	Url         string    `json:"url"`
}

func (q *Queries) ReplaceSocialLink(ctx context.Context, arg ReplaceSocialLinkParams) (NonprofitSocialLink, error) {
	row := q.db.QueryRowContext(ctx, replaceSocialLink, arg.NonprofitID, arg.Platform, arg.Url)
	var i NonprofitSocialLink
	err := row.Scan(
		&i.ID,
		&i.NonprofitID,
		&i.Platform,
		&i.Url,
	)
	return i, err
}

const searchNonprofits = `-- name: SearchNonprofits :many
SELECT
    id, name, slug, description, image, address, phone, ein, "hasToPay", website, categories, follower_count, total_raised_cents, raffles_run, created_at, updated_at
FROM
    nonprofits
WHERE
    name ILIKE '%' || $1 || '%'
ORDER BY
    follower_count DESC
LIMIT
    $3 OFFSET $2
`

type SearchNonprofitsParams struct {
	Query        sql.NullString `json:"query"`
	ResultOffset int32          `json:"result_offset"`
	ResultLimit  int32          `json:"result_limit"`
}

func (q *Queries) SearchNonprofits(ctx context.Context, arg SearchNonprofitsParams) ([]Nonprofit, error) {
	rows, err := q.db.QueryContext(ctx, searchNonprofits, arg.Query, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Nonprofit{}
	for rows.Next() {
		var i Nonprofit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Image,
			&i.Address,
			&i.Phone,
			&i.Ein,
			&i.HasToPay,
			&i.Website,
			pq.Array(&i.Categories),
			&i.FollowerCount,
			&i.TotalRaisedCents,
			&i.RafflesRun,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNonprofitContact = `-- name: UpdateNonprofitContact :one
UPDATE
    nonprofits
SET
    website = $2,
    phone = $3,
    address = $4
WHERE
    id = $1
RETURNING
    id, name, slug, description, image, address, phone, ein, "hasToPay", website, categories, follower_count, total_raised_cents, raffles_run, created_at, updated_at
`

type UpdateNonprofitContactParams struct {
	ID      uuid.UUID      `json:"id"`
	Website sql.NullString `json:"website"`
	Phone   sql.NullString `json:"phone"`
	Address sql.NullString `json:"address"`
}

func (q *Queries) UpdateNonprofitContact(ctx context.Context, arg UpdateNonprofitContactParams) (Nonprofit, error) {
	row := q.db.QueryRowContext(ctx, updateNonprofitContact,
		arg.ID,
		arg.Website,
		arg.Phone,
		arg.Address,
	)
	var i Nonprofit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Address,
		&i.Phone,
		&i.Ein,
		&i.HasToPay,
		&i.Website,
		pq.Array(&i.Categories),
		&i.FollowerCount,
		&i.TotalRaisedCents,
		&i.RafflesRun,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNonprofitProfile = `-- name: UpdateNonprofitProfile :one
UPDATE
    nonprofits
SET
    name = $2,
    description = $3,
    image = $4,
    categories = $5
WHERE
    id = $1
RETURNING
    id, name, slug, description, image, address, phone, ein, "hasToPay", website, categories, follower_count, total_raised_cents, raffles_run, created_at, updated_at
`

type UpdateNonprofitProfileParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Image       sql.NullString `json:"image"`
	Categories  []string       `json:"categories"`
}

func (q *Queries) UpdateNonprofitProfile(ctx context.Context, arg UpdateNonprofitProfileParams) (Nonprofit, error) {
	row := q.db.QueryRowContext(ctx, updateNonprofitProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Image,
		pq.Array(arg.Categories),
	)
	var i Nonprofit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Address,
		&i.Phone,
		&i.Ein,
		&i.HasToPay,
		&i.Website,
		pq.Array(&i.Categories),
		&i.FollowerCount,
		&i.TotalRaisedCents,
		&i.RafflesRun,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :one
UPDATE
    nonprofit_users
SET
    role = $3
WHERE
    nonprofit_id = $1
    AND user_id = $2
RETURNING
    id, nonprofit_id, user_id, role, mode, created_at, updated_at
`

type UpdateTeamMemberRoleParams struct {
	NonprofitID uuid.UUID `json:"nonprofit_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (NonprofitUser, error) {
	row := q.db.QueryRowContext(ctx, updateTeamMemberRole, arg.NonprofitID, arg.UserID, arg.Role)
	var i NonprofitUser
	err := row.Scan(
		&i.ID,
		&i.NonprofitID,
		&i.UserID,
		&i.Role,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBankAccount = `-- name: UpsertBankAccount :one
INSERT INTO
    nonprofit_bank_accounts (
        nonprofit_id,
        processor,
        processor_account_id,
        bank_name,
        last4,
        account_type,
        is_verified
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, nonprofit_id, processor, processor_account_id, bank_name, last4, account_type, is_verified, created_at, updated_at
`

type UpsertBankAccountParams struct {
	NonprofitID        uuid.UUID      `json:"nonprofit_id"`
	Processor          string         `json:"processor"`
	ProcessorAccountID string         `json:"processor_account_id"`
	BankName           sql.NullString `json:"bank_name"`
	Last4              sql.NullString `json:"last4"`
	AccountType        sql.NullString `json:"account_type"`
	IsVerified         bool           `json:"is_verified"`
}

func (q *Queries) UpsertBankAccount(ctx context.Context, arg UpsertBankAccountParams) (NonprofitBankAccount, error) {
	row := q.db.QueryRowContext(ctx, upsertBankAccount,
		arg.NonprofitID,
		arg.Processor,
		arg.ProcessorAccountID,
		arg.BankName,
		arg.Last4,
		arg.AccountType,
		arg.IsVerified,
	)
	var i NonprofitBankAccount
	err := row.Scan(
		&i.ID,
		&i.NonprofitID,
		&i.Processor,
		&i.ProcessorAccountID,
		&i.BankName,
		&i.Last4,
		&i.AccountType,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
