// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nonprofit_raffles.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const listNonprofitRaffles = `-- name: ListNonprofitRaffles :many
SELECT
    id,
    title,
    slug,
    description,
    status,
    ticket_strategy,
    ticket_assignment_strategy,
    draw_strategy,
    ticket_price,
    max_tickets,
    tickets_sold,
    attributes,
    image_urls,
    draw_at,
    drawn_at,
    category_id,
    category_path,
    created_at,
    updated_at
FROM raffle_items
WHERE created_by = $1::uuid
  AND (
    CASE $2::text
        WHEN 'active' THEN status = 'active'
        WHEN 'past'   THEN status = 'completed'
        ELSE status IN ('active', 'completed')
    END
  )
ORDER BY
    -- active raffles: ending soonest first; everything else: newest first
    CASE WHEN status = 'active' THEN draw_at END ASC NULLS LAST,
    created_at DESC
LIMIT $4
OFFSET $3
`

type ListNonprofitRafflesParams struct {
	NonprofitID  uuid.UUID `json:"nonprofit_id"`
	StatusFilter string    `json:"status_filter"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

type ListNonprofitRafflesRow struct {
	ID                       uuid.UUID                `json:"id"`
	Title                    string                   `json:"title"`
	Slug                     sql.NullString           `json:"slug"`
	Description              sql.NullString           `json:"description"`
	Status                   RaffleItemStatus         `json:"status"`
	TicketStrategy           TicketStrategy           `json:"ticket_strategy"`
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	DrawStrategy             DrawStrategy             `json:"draw_strategy"`
	TicketPrice              sql.NullString           `json:"ticket_price"`
	MaxTickets               sql.NullInt32            `json:"max_tickets"`
	TicketsSold              int32                    `json:"tickets_sold"`
	Attributes               json.RawMessage          `json:"attributes"`
	ImageUrls                []string                 `json:"image_urls"`
	DrawAt                   sql.NullTime             `json:"draw_at"`
	DrawnAt                  sql.NullTime             `json:"drawn_at"`
	CategoryID               uuid.UUID                `json:"category_id"`
	CategoryPath             string                   `json:"category_path"`
	CreatedAt                time.Time                `json:"created_at"`
	UpdatedAt                time.Time                `json:"updated_at"`
}

// Public list of one nonprofit's raffles, for the org profile screen.
//
//	status_filter: 'active' | 'past' | 'all'
//
// Drafts and cancelled raffles are never returned (this is the public view).
// Reads straight from raffle_items — the client adapter only needs these columns,
// so no category/nonprofit joins are required here.
func (q *Queries) ListNonprofitRaffles(ctx context.Context, arg ListNonprofitRafflesParams) ([]ListNonprofitRafflesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNonprofitRaffles,
		arg.NonprofitID,
		arg.StatusFilter,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNonprofitRafflesRow{}
	for rows.Next() {
		var i ListNonprofitRafflesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.TicketAssignmentStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.DrawAt,
			&i.DrawnAt,
			&i.CategoryID,
			&i.CategoryPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
