// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nonprofits_list.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const listNonprofits = `-- name: ListNonprofits :many
SELECT
    n.id,
    n.name,
    n.description,
    n.image,
    n.ein,
    n.categories,
    n.follower_count,
    n.total_raised_cents,
    COALESCE(v."isVerified", FALSE)::bool AS is_verified,
    COALESCE((
        SELECT COUNT(*) FROM raffle_items ri
        WHERE ri.created_by = n.id
          AND ri.status = 'active'::raffle_item_status
    ), 0)::int AS active_raffles,
    COALESCE((
        SELECT TRUE FROM org_follows f
        WHERE f.nonprofit_id = n.id
          AND f.user_id = $1
    ), FALSE)::bool AS is_following
FROM nonprofits n
LEFT JOIN LATERAL (
    SELECT nv."isVerified"
    FROM nonprofit_verifications nv
    WHERE nv.nonprofit_id = n.id
    ORDER BY nv.created_at DESC
    LIMIT 1
) v ON TRUE
WHERE (
    $2::text IS NULL
    OR n.name ILIKE '%' || $2::text || '%'
)
ORDER BY
    CASE WHEN $3::text = 'most_raised' THEN n.total_raised_cents END DESC NULLS LAST,
    CASE WHEN $3::text = 'most_active' THEN (
        SELECT COUNT(*) FROM raffle_items ri
        WHERE ri.created_by = n.id AND ri.status = 'active'::raffle_item_status
    ) END DESC NULLS LAST,
    CASE WHEN $3::text = 'alphabetical' THEN n.name END ASC NULLS LAST,
    n.follower_count DESC,   -- default = most followed
    n.name
LIMIT $5 OFFSET $4
`

type ListNonprofitsParams struct {
	ViewerID     uuid.NullUUID  `json:"viewer_id"`
	Search       sql.NullString `json:"search"`
	Sort         string         `json:"sort"`
	ResultOffset int32          `json:"result_offset"`
	ResultLimit  int32          `json:"result_limit"`
}

type ListNonprofitsRow struct {
	ID               uuid.UUID      `json:"id"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Image            sql.NullString `json:"image"`
	Ein              sql.NullString `json:"ein"`
	Categories       []string       `json:"categories"`
	FollowerCount    int32          `json:"follower_count"`
	TotalRaisedCents int64          `json:"total_raised_cents"`
	IsVerified       bool           `json:"is_verified"`
	ActiveRaffles    int32          `json:"active_raffles"`
	IsFollowing      bool           `json:"is_following"`
}

// sort: 'most_followed' (default) | 'most_raised' | 'most_active' | 'alphabetical'
func (q *Queries) ListNonprofits(ctx context.Context, arg ListNonprofitsParams) ([]ListNonprofitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNonprofits,
		arg.ViewerID,
		arg.Search,
		arg.Sort,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNonprofitsRow{}
	for rows.Next() {
		var i ListNonprofitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			&i.Ein,
			pq.Array(&i.Categories),
			&i.FollowerCount,
			&i.TotalRaisedCents,
			&i.IsVerified,
			&i.ActiveRaffles,
			&i.IsFollowing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
