// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: priceTiers.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPrizeTier = `-- name: CreatePrizeTier :one
INSERT INTO
    prize_tiers (
        raffle_item_id,
        rank,
        title,
        description,
        value_cents,
        image_url
    )
VALUES
    ($1, $2, $3, $4, $5, $6)
RETURNING
    id, raffle_item_id, rank, title, description, value_cents, image_url
`

type CreatePrizeTierParams struct {
	RaffleItemID uuid.UUID      `json:"raffle_item_id"`
	Rank         int32          `json:"rank"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	ValueCents   sql.NullInt32  `json:"value_cents"`
	ImageUrl     sql.NullString `json:"image_url"`
}

func (q *Queries) CreatePrizeTier(ctx context.Context, arg CreatePrizeTierParams) (PrizeTier, error) {
	row := q.db.QueryRowContext(ctx, createPrizeTier,
		arg.RaffleItemID,
		arg.Rank,
		arg.Title,
		arg.Description,
		arg.ValueCents,
		arg.ImageUrl,
	)
	var i PrizeTier
	err := row.Scan(
		&i.ID,
		&i.RaffleItemID,
		&i.Rank,
		&i.Title,
		&i.Description,
		&i.ValueCents,
		&i.ImageUrl,
	)
	return i, err
}

const deletePrizeTiersForRaffle = `-- name: DeletePrizeTiersForRaffle :exec
DELETE FROM
    prize_tiers
WHERE
    raffle_item_id = $1
`

func (q *Queries) DeletePrizeTiersForRaffle(ctx context.Context, raffleItemID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePrizeTiersForRaffle, raffleItemID)
	return err
}

const listPrizeTiers = `-- name: ListPrizeTiers :many
SELECT
    id, raffle_item_id, rank, title, description, value_cents, image_url
FROM
    prize_tiers
WHERE
    raffle_item_id = $1
ORDER BY
    rank
`

func (q *Queries) ListPrizeTiers(ctx context.Context, raffleItemID uuid.UUID) ([]PrizeTier, error) {
	rows, err := q.db.QueryContext(ctx, listPrizeTiers, raffleItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrizeTier{}
	for rows.Next() {
		var i PrizeTier
		if err := rows.Scan(
			&i.ID,
			&i.RaffleItemID,
			&i.Rank,
			&i.Title,
			&i.Description,
			&i.ValueCents,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
