// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addPaymentMethod = `-- name: AddPaymentMethod :one
INSERT INTO
    payment_methods (
        user_id,
        processor,
        processor_pm_id,
        brand,
        last4,
        exp_month,
        exp_year,
        is_default
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id, user_id, processor, processor_pm_id, brand, last4, exp_month, exp_year, is_default, created_at
`

type AddPaymentMethodParams struct {
	UserID        uuid.UUID `json:"user_id"`
	Processor     string    `json:"processor"`
	ProcessorPmID string    `json:"processor_pm_id"`
	Brand         string    `json:"brand"`
	Last4         string    `json:"last4"`
	ExpMonth      int32     `json:"exp_month"`
	ExpYear       int32     `json:"exp_year"`
	IsDefault     bool      `json:"is_default"`
}

func (q *Queries) AddPaymentMethod(ctx context.Context, arg AddPaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, addPaymentMethod,
		arg.UserID,
		arg.Processor,
		arg.ProcessorPmID,
		arg.Brand,
		arg.Last4,
		arg.ExpMonth,
		arg.ExpYear,
		arg.IsDefault,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Processor,
		&i.ProcessorPmID,
		&i.Brand,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const addShippingAddress = `-- name: AddShippingAddress :one
INSERT INTO
    shipping_addresses (
        user_id,
        line1,
        line2,
        city,
        state,
        zip,
        country,
        is_default
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id, user_id, line1, line2, city, state, zip, country, is_default, created_at
`

type AddShippingAddressParams struct {
	UserID    uuid.UUID      `json:"user_id"`
	Line1     string         `json:"line1"`
	Line2     sql.NullString `json:"line2"`
	City      string         `json:"city"`
	State     string         `json:"state"`
	Zip       string         `json:"zip"`
	Country   string         `json:"country"`
	IsDefault bool           `json:"is_default"`
}

func (q *Queries) AddShippingAddress(ctx context.Context, arg AddShippingAddressParams) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, addShippingAddress,
		arg.UserID,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Country,
		arg.IsDefault,
	)
	var i ShippingAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const deletePaymentMethod = `-- name: DeletePaymentMethod :exec
DELETE FROM
    payment_methods
WHERE
    id = $1
    AND user_id = $2
`

type DeletePaymentMethodParams struct {
	PaymentMethodID uuid.UUID `json:"payment_method_id"`
	UserID          uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePaymentMethod(ctx context.Context, arg DeletePaymentMethodParams) error {
	_, err := q.db.ExecContext(ctx, deletePaymentMethod, arg.PaymentMethodID, arg.UserID)
	return err
}

const deleteShippingAddress = `-- name: DeleteShippingAddress :exec
DELETE FROM
    shipping_addresses
WHERE
    id = $1
    AND user_id = $2
`

type DeleteShippingAddressParams struct {
	AddressID uuid.UUID `json:"address_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteShippingAddress(ctx context.Context, arg DeleteShippingAddressParams) error {
	_, err := q.db.ExecContext(ctx, deleteShippingAddress, arg.AddressID, arg.UserID)
	return err
}

const getDefaultPaymentMethod = `-- name: GetDefaultPaymentMethod :one
SELECT
    id, user_id, processor, processor_pm_id, brand, last4, exp_month, exp_year, is_default, created_at
FROM
    payment_methods
WHERE
    user_id = $1
    AND is_default = TRUE
LIMIT
    1
`

func (q *Queries) GetDefaultPaymentMethod(ctx context.Context, userID uuid.UUID) (PaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, getDefaultPaymentMethod, userID)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Processor,
		&i.ProcessorPmID,
		&i.Brand,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultShippingAddress = `-- name: GetDefaultShippingAddress :one
SELECT
    id, user_id, line1, line2, city, state, zip, country, is_default, created_at
FROM
    shipping_addresses
WHERE
    user_id = $1
    AND is_default = TRUE
LIMIT
    1
`

func (q *Queries) GetDefaultShippingAddress(ctx context.Context, userID uuid.UUID) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, getDefaultShippingAddress, userID)
	var i ShippingAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgNotificationPrefs = `-- name: GetOrgNotificationPrefs :one
SELECT
    id, user_id, nonprofit_id, prefs, updated_at
FROM
    notification_preferences
WHERE
    nonprofit_id = $1
`

func (q *Queries) GetOrgNotificationPrefs(ctx context.Context, nonprofitID uuid.NullUUID) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, getOrgNotificationPrefs, nonprofitID)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NonprofitID,
		&i.Prefs,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserNotificationPrefs = `-- name: GetUserNotificationPrefs :one
SELECT
    id, user_id, nonprofit_id, prefs, updated_at
FROM
    notification_preferences
WHERE
    user_id = $1
`

// ── Notification preferences ──────────────────────────────────────────────────
func (q *Queries) GetUserNotificationPrefs(ctx context.Context, userID uuid.NullUUID) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserNotificationPrefs, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NonprofitID,
		&i.Prefs,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT
    id, user_id, processor, processor_pm_id, brand, last4, exp_month, exp_year, is_default, created_at
FROM
    payment_methods
WHERE
    user_id = $1
ORDER BY
    is_default DESC,
    created_at DESC
`

// ── Payment methods ───────────────────────────────────────────────────────────
func (q *Queries) ListPaymentMethods(ctx context.Context, userID uuid.UUID) ([]PaymentMethod, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentMethods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentMethod{}
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Processor,
			&i.ProcessorPmID,
			&i.Brand,
			&i.Last4,
			&i.ExpMonth,
			&i.ExpYear,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingAddresses = `-- name: ListShippingAddresses :many
SELECT
    id, user_id, line1, line2, city, state, zip, country, is_default, created_at
FROM
    shipping_addresses
WHERE
    user_id = $1
ORDER BY
    is_default DESC,
    created_at DESC
`

// ── Shipping addresses ────────────────────────────────────────────────────────
func (q *Queries) ListShippingAddresses(ctx context.Context, userID uuid.UUID) ([]ShippingAddress, error) {
	rows, err := q.db.QueryContext(ctx, listShippingAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingAddress{}
	for rows.Next() {
		var i ShippingAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Country,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultPaymentMethod = `-- name: SetDefaultPaymentMethod :exec
UPDATE
    payment_methods
SET
    is_default = (id = $1)
WHERE
    user_id = $2
`

type SetDefaultPaymentMethodParams struct {
	PaymentMethodID uuid.UUID `json:"payment_method_id"`
	UserID          uuid.UUID `json:"user_id"`
}

// Clear other defaults, then set this one (call in a tx).
func (q *Queries) SetDefaultPaymentMethod(ctx context.Context, arg SetDefaultPaymentMethodParams) error {
	_, err := q.db.ExecContext(ctx, setDefaultPaymentMethod, arg.PaymentMethodID, arg.UserID)
	return err
}

const setDefaultShippingAddress = `-- name: SetDefaultShippingAddress :exec
UPDATE
    shipping_addresses
SET
    is_default = (id = $1)
WHERE
    user_id = $2
`

type SetDefaultShippingAddressParams struct {
	AddressID uuid.UUID `json:"address_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) SetDefaultShippingAddress(ctx context.Context, arg SetDefaultShippingAddressParams) error {
	_, err := q.db.ExecContext(ctx, setDefaultShippingAddress, arg.AddressID, arg.UserID)
	return err
}

const updateShippingAddress = `-- name: UpdateShippingAddress :one
UPDATE
    shipping_addresses
SET
    line1 = $1,
    line2 = $2,
    city = $3,
    state = $4,
    zip = $5,
    country = $6
WHERE
    id = $7
    AND user_id = $8
RETURNING
    id, user_id, line1, line2, city, state, zip, country, is_default, created_at
`

type UpdateShippingAddressParams struct {
	Line1     string         `json:"line1"`
	Line2     sql.NullString `json:"line2"`
	City      string         `json:"city"`
	State     string         `json:"state"`
	Zip       string         `json:"zip"`
	Country   string         `json:"country"`
	AddressID uuid.UUID      `json:"address_id"`
	UserID    uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateShippingAddress(ctx context.Context, arg UpdateShippingAddressParams) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, updateShippingAddress,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Country,
		arg.AddressID,
		arg.UserID,
	)
	var i ShippingAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserLocationRegion = `-- name: UpdateUserLocationRegion :exec
UPDATE
    users
SET
    location_region = $2
WHERE
    id = $1
`

type UpdateUserLocationRegionParams struct {
	ID             uuid.UUID      `json:"id"`
	LocationRegion sql.NullString `json:"location_region"`
}

func (q *Queries) UpdateUserLocationRegion(ctx context.Context, arg UpdateUserLocationRegionParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLocationRegion, arg.ID, arg.LocationRegion)
	return err
}

const updateUserPreferredCategories = `-- name: UpdateUserPreferredCategories :exec
UPDATE
    users
SET
    preferred_categories = $2
WHERE
    id = $1
`

type UpdateUserPreferredCategoriesParams struct {
	ID                  uuid.UUID `json:"id"`
	PreferredCategories []string  `json:"preferred_categories"`
}

// ── User profile basics + stats ───────────────────────────────────────────────
func (q *Queries) UpdateUserPreferredCategories(ctx context.Context, arg UpdateUserPreferredCategoriesParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPreferredCategories, arg.ID, pq.Array(arg.PreferredCategories))
	return err
}

const upsertOrgNotificationPrefs = `-- name: UpsertOrgNotificationPrefs :one
INSERT INTO
    notification_preferences (nonprofit_id, prefs)
VALUES
    ($1, $2) ON CONFLICT (nonprofit_id) DO
UPDATE
SET
    prefs = EXCLUDED.prefs,
    updated_at = NOW()
RETURNING
    id, user_id, nonprofit_id, prefs, updated_at
`

type UpsertOrgNotificationPrefsParams struct {
	NonprofitID uuid.NullUUID   `json:"nonprofit_id"`
	Prefs       json.RawMessage `json:"prefs"`
}

func (q *Queries) UpsertOrgNotificationPrefs(ctx context.Context, arg UpsertOrgNotificationPrefsParams) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, upsertOrgNotificationPrefs, arg.NonprofitID, arg.Prefs)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NonprofitID,
		&i.Prefs,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserNotificationPrefs = `-- name: UpsertUserNotificationPrefs :one
INSERT INTO
    notification_preferences (user_id, prefs)
VALUES
    ($1, $2) ON CONFLICT (user_id) DO
UPDATE
SET
    prefs = EXCLUDED.prefs,
    updated_at = NOW()
RETURNING
    id, user_id, nonprofit_id, prefs, updated_at
`

type UpsertUserNotificationPrefsParams struct {
	UserID uuid.NullUUID   `json:"user_id"`
	Prefs  json.RawMessage `json:"prefs"`
}

func (q *Queries) UpsertUserNotificationPrefs(ctx context.Context, arg UpsertUserNotificationPrefsParams) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, upsertUserNotificationPrefs, arg.UserID, arg.Prefs)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NonprofitID,
		&i.Prefs,
		&i.UpdatedAt,
	)
	return i, err
}
