// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: raffles.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countRafflesByStatusForNonprofit = `-- name: CountRafflesByStatusForNonprofit :many
SELECT
    STATUS,
    COUNT(*)::INT AS count
FROM
    raffle_items
WHERE
    created_by = $1
GROUP BY
    STATUS
`

type CountRafflesByStatusForNonprofitRow struct {
	Status RaffleItemStatus `json:"status"`
	Count  int32            `json:"count"`
}

// For the manage-raffles header counts.
func (q *Queries) CountRafflesByStatusForNonprofit(ctx context.Context, createdBy uuid.NullUUID) ([]CountRafflesByStatusForNonprofitRow, error) {
	rows, err := q.db.QueryContext(ctx, countRafflesByStatusForNonprofit, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRafflesByStatusForNonprofitRow{}
	for rows.Next() {
		var i CountRafflesByStatusForNonprofitRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRaffle = `-- name: CreateRaffle :one
INSERT INTO
    raffle_items (
        category_id,
        title,
        slug,
        description,
        STATUS,
        ticket_strategy,
        ticket_assignment_strategy,
        draw_strategy,
        ticket_price,
        free_tickets,
        free_ticket_start_range,
        free_ticket_end_range,
        max_tickets,
        attributes,
        image_urls,
        draw_at,
        created_by
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17
    )
RETURNING
    id, category_id, category_path, title, slug, description, status, ticket_strategy, ticket_assignment_strategy, draw_strategy, ticket_price, free_tickets, free_ticket_start_range, free_ticket_end_range, max_tickets, tickets_sold, attributes, image_urls, draw_at, drawn_at, created_by, created_at, updated_at
`

type CreateRaffleParams struct {
	CategoryID               uuid.UUID                `json:"category_id"`
	Title                    string                   `json:"title"`
	Slug                     sql.NullString           `json:"slug"`
	Description              sql.NullString           `json:"description"`
	Status                   RaffleItemStatus         `json:"status"`
	TicketStrategy           TicketStrategy           `json:"ticket_strategy"`
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	DrawStrategy             DrawStrategy             `json:"draw_strategy"`
	TicketPrice              sql.NullString           `json:"ticket_price"`
	FreeTickets              int32                    `json:"free_tickets"`
	FreeTicketStartRange     sql.NullInt32            `json:"free_ticket_start_range"`
	FreeTicketEndRange       sql.NullInt32            `json:"free_ticket_end_range"`
	MaxTickets               sql.NullInt32            `json:"max_tickets"`
	Attributes               json.RawMessage          `json:"attributes"`
	ImageUrls                []string                 `json:"image_urls"`
	DrawAt                   sql.NullTime             `json:"draw_at"`
	CreatedBy                uuid.NullUUID            `json:"created_by"`
}

// ── Create / update / lifecycle ───────────────────────────────────────────────
func (q *Queries) CreateRaffle(ctx context.Context, arg CreateRaffleParams) (RaffleItem, error) {
	row := q.db.QueryRowContext(ctx, createRaffle,
		arg.CategoryID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Status,
		arg.TicketStrategy,
		arg.TicketAssignmentStrategy,
		arg.DrawStrategy,
		arg.TicketPrice,
		arg.FreeTickets,
		arg.FreeTicketStartRange,
		arg.FreeTicketEndRange,
		arg.MaxTickets,
		arg.Attributes,
		pq.Array(arg.ImageUrls),
		arg.DrawAt,
		arg.CreatedBy,
	)
	var i RaffleItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.CategoryPath,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.TicketStrategy,
		&i.TicketAssignmentStrategy,
		&i.DrawStrategy,
		&i.TicketPrice,
		&i.FreeTickets,
		&i.FreeTicketStartRange,
		&i.FreeTicketEndRange,
		&i.MaxTickets,
		&i.TicketsSold,
		&i.Attributes,
		pq.Array(&i.ImageUrls),
		&i.DrawAt,
		&i.DrawnAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRaffle = `-- name: DeleteRaffle :exec
DELETE FROM
    raffle_items
WHERE
    id = $1
    AND created_by = $2
    AND STATUS = 'draft'
`

type DeleteRaffleParams struct {
	RaffleID    uuid.UUID     `json:"raffle_id"`
	NonprofitID uuid.NullUUID `json:"nonprofit_id"`
}

func (q *Queries) DeleteRaffle(ctx context.Context, arg DeleteRaffleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRaffle, arg.RaffleID, arg.NonprofitID)
	return err
}

const filterRafflesByAttribute = `-- name: FilterRafflesByAttribute :many
SELECT
    id, title, slug, description, status, ticket_strategy, draw_strategy, ticket_price, max_tickets, tickets_sold, draw_at, attributes, image_urls, category_path, nonprofit_id, category_id, category_name, category_slug, category_icon, category_depth
FROM
    v_active_raffles
WHERE
    attributes @> $1
ORDER BY
    tickets_sold DESC
LIMIT
    $3 OFFSET $2
`

type FilterRafflesByAttributeParams struct {
	AttributeFilter json.RawMessage `json:"attribute_filter"`
	ResultOffset    int32           `json:"result_offset"`
	ResultLimit     int32           `json:"result_limit"`
}

// JSONB attribute filter, e.g. attributes @> '{"brand":"Nike"}'.
func (q *Queries) FilterRafflesByAttribute(ctx context.Context, arg FilterRafflesByAttributeParams) ([]VActiveRaffle, error) {
	rows, err := q.db.QueryContext(ctx, filterRafflesByAttribute, arg.AttributeFilter, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VActiveRaffle{}
	for rows.Next() {
		var i VActiveRaffle
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.DrawAt,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.CategoryPath,
			&i.NonprofitID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryIcon,
			&i.CategoryDepth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRaffleByID = `-- name: GetRaffleByID :one
SELECT
    ri.id, ri.category_id, ri.category_path, ri.title, ri.slug, ri.description, ri.status, ri.ticket_strategy, ri.ticket_assignment_strategy, ri.draw_strategy, ri.ticket_price, ri.free_tickets, ri.free_ticket_start_range, ri.free_ticket_end_range, ri.max_tickets, ri.tickets_sold, ri.attributes, ri.image_urls, ri.draw_at, ri.drawn_at, ri.created_by, ri.created_at, ri.updated_at,
    c.name AS category_name,
    c.slug AS category_slug,
    c.icon AS category_icon,
    n.name AS nonprofit_name,
    n.slug AS nonprofit_slug,
    n.image AS nonprofit_image
FROM
    raffle_items ri
    JOIN categories c ON c.id = ri.category_id
    LEFT JOIN nonprofits n ON n.id = ri.created_by
WHERE
    ri.id = $1
`

type GetRaffleByIDRow struct {
	ID                       uuid.UUID                `json:"id"`
	CategoryID               uuid.UUID                `json:"category_id"`
	CategoryPath             string                   `json:"category_path"`
	Title                    string                   `json:"title"`
	Slug                     sql.NullString           `json:"slug"`
	Description              sql.NullString           `json:"description"`
	Status                   RaffleItemStatus         `json:"status"`
	TicketStrategy           TicketStrategy           `json:"ticket_strategy"`
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	DrawStrategy             DrawStrategy             `json:"draw_strategy"`
	TicketPrice              sql.NullString           `json:"ticket_price"`
	FreeTickets              int32                    `json:"free_tickets"`
	FreeTicketStartRange     sql.NullInt32            `json:"free_ticket_start_range"`
	FreeTicketEndRange       sql.NullInt32            `json:"free_ticket_end_range"`
	MaxTickets               sql.NullInt32            `json:"max_tickets"`
	TicketsSold              int32                    `json:"tickets_sold"`
	Attributes               json.RawMessage          `json:"attributes"`
	ImageUrls                []string                 `json:"image_urls"`
	DrawAt                   sql.NullTime             `json:"draw_at"`
	DrawnAt                  sql.NullTime             `json:"drawn_at"`
	CreatedBy                uuid.NullUUID            `json:"created_by"`
	CreatedAt                time.Time                `json:"created_at"`
	UpdatedAt                time.Time                `json:"updated_at"`
	CategoryName             string                   `json:"category_name"`
	CategorySlug             string                   `json:"category_slug"`
	CategoryIcon             sql.NullString           `json:"category_icon"`
	NonprofitName            sql.NullString           `json:"nonprofit_name"`
	NonprofitSlug            sql.NullString           `json:"nonprofit_slug"`
	NonprofitImage           sql.NullString           `json:"nonprofit_image"`
}

func (q *Queries) GetRaffleByID(ctx context.Context, id uuid.UUID) (GetRaffleByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRaffleByID, id)
	var i GetRaffleByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.CategoryPath,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.TicketStrategy,
		&i.TicketAssignmentStrategy,
		&i.DrawStrategy,
		&i.TicketPrice,
		&i.FreeTickets,
		&i.FreeTicketStartRange,
		&i.FreeTicketEndRange,
		&i.MaxTickets,
		&i.TicketsSold,
		&i.Attributes,
		pq.Array(&i.ImageUrls),
		&i.DrawAt,
		&i.DrawnAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategorySlug,
		&i.CategoryIcon,
		&i.NonprofitName,
		&i.NonprofitSlug,
		&i.NonprofitImage,
	)
	return i, err
}

const getRaffleBySlug = `-- name: GetRaffleBySlug :one
SELECT
    ri.id, ri.category_id, ri.category_path, ri.title, ri.slug, ri.description, ri.status, ri.ticket_strategy, ri.ticket_assignment_strategy, ri.draw_strategy, ri.ticket_price, ri.free_tickets, ri.free_ticket_start_range, ri.free_ticket_end_range, ri.max_tickets, ri.tickets_sold, ri.attributes, ri.image_urls, ri.draw_at, ri.drawn_at, ri.created_by, ri.created_at, ri.updated_at,
    c.name AS category_name,
    c.slug AS category_slug,
    c.icon AS category_icon,
    n.name AS nonprofit_name,
    n.slug AS nonprofit_slug,
    n.image AS nonprofit_image
FROM
    raffle_items ri
    JOIN categories c ON c.id = ri.category_id
    LEFT JOIN nonprofits n ON n.id = ri.created_by
WHERE
    ri.slug = $1::text
`

type GetRaffleBySlugRow struct {
	ID                       uuid.UUID                `json:"id"`
	CategoryID               uuid.UUID                `json:"category_id"`
	CategoryPath             string                   `json:"category_path"`
	Title                    string                   `json:"title"`
	Slug                     sql.NullString           `json:"slug"`
	Description              sql.NullString           `json:"description"`
	Status                   RaffleItemStatus         `json:"status"`
	TicketStrategy           TicketStrategy           `json:"ticket_strategy"`
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	DrawStrategy             DrawStrategy             `json:"draw_strategy"`
	TicketPrice              sql.NullString           `json:"ticket_price"`
	FreeTickets              int32                    `json:"free_tickets"`
	FreeTicketStartRange     sql.NullInt32            `json:"free_ticket_start_range"`
	FreeTicketEndRange       sql.NullInt32            `json:"free_ticket_end_range"`
	MaxTickets               sql.NullInt32            `json:"max_tickets"`
	TicketsSold              int32                    `json:"tickets_sold"`
	Attributes               json.RawMessage          `json:"attributes"`
	ImageUrls                []string                 `json:"image_urls"`
	DrawAt                   sql.NullTime             `json:"draw_at"`
	DrawnAt                  sql.NullTime             `json:"drawn_at"`
	CreatedBy                uuid.NullUUID            `json:"created_by"`
	CreatedAt                time.Time                `json:"created_at"`
	UpdatedAt                time.Time                `json:"updated_at"`
	CategoryName             string                   `json:"category_name"`
	CategorySlug             string                   `json:"category_slug"`
	CategoryIcon             sql.NullString           `json:"category_icon"`
	NonprofitName            sql.NullString           `json:"nonprofit_name"`
	NonprofitSlug            sql.NullString           `json:"nonprofit_slug"`
	NonprofitImage           sql.NullString           `json:"nonprofit_image"`
}

func (q *Queries) GetRaffleBySlug(ctx context.Context, slug string) (GetRaffleBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getRaffleBySlug, slug)
	var i GetRaffleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.CategoryPath,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.TicketStrategy,
		&i.TicketAssignmentStrategy,
		&i.DrawStrategy,
		&i.TicketPrice,
		&i.FreeTickets,
		&i.FreeTicketStartRange,
		&i.FreeTicketEndRange,
		&i.MaxTickets,
		&i.TicketsSold,
		&i.Attributes,
		pq.Array(&i.ImageUrls),
		&i.DrawAt,
		&i.DrawnAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategorySlug,
		&i.CategoryIcon,
		&i.NonprofitName,
		&i.NonprofitSlug,
		&i.NonprofitImage,
	)
	return i, err
}

const listActiveRaffles = `-- name: ListActiveRaffles :many
SELECT
    id, title, slug, description, status, ticket_strategy, draw_strategy, ticket_price, max_tickets, tickets_sold, draw_at, attributes, image_urls, category_path, nonprofit_id, category_id, category_name, category_slug, category_icon, category_depth
FROM
    v_active_raffles
ORDER BY
    draw_at NULLS LAST
LIMIT
    $2 OFFSET $1
`

type ListActiveRafflesParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

// ── Browse / feed (participant) ──────────────────────────────────────────────
// General feed, newest first.
func (q *Queries) ListActiveRaffles(ctx context.Context, arg ListActiveRafflesParams) ([]VActiveRaffle, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRaffles, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VActiveRaffle{}
	for rows.Next() {
		var i VActiveRaffle
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.DrawAt,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.CategoryPath,
			&i.NonprofitID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryIcon,
			&i.CategoryDepth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRafflesForNonprofit = `-- name: ListActiveRafflesForNonprofit :many
SELECT
    ri.id, ri.category_id, ri.category_path, ri.title, ri.slug, ri.description, ri.status, ri.ticket_strategy, ri.ticket_assignment_strategy, ri.draw_strategy, ri.ticket_price, ri.free_tickets, ri.free_ticket_start_range, ri.free_ticket_end_range, ri.max_tickets, ri.tickets_sold, ri.attributes, ri.image_urls, ri.draw_at, ri.drawn_at, ri.created_by, ri.created_at, ri.updated_at,
    c.name AS category_name
FROM
    raffle_items ri
    JOIN categories c ON c.id = ri.category_id
WHERE
    ri.created_by = $1
    AND ri.status IN ('active', 'drawing')
ORDER BY
    ri.draw_at NULLS LAST
LIMIT
    $2
`

type ListActiveRafflesForNonprofitParams struct {
	NonprofitID uuid.NullUUID `json:"nonprofit_id"`
	ResultLimit int32         `json:"result_limit"`
}

type ListActiveRafflesForNonprofitRow struct {
	ID                       uuid.UUID                `json:"id"`
	CategoryID               uuid.UUID                `json:"category_id"`
	CategoryPath             string                   `json:"category_path"`
	Title                    string                   `json:"title"`
	Slug                     sql.NullString           `json:"slug"`
	Description              sql.NullString           `json:"description"`
	Status                   RaffleItemStatus         `json:"status"`
	TicketStrategy           TicketStrategy           `json:"ticket_strategy"`
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	DrawStrategy             DrawStrategy             `json:"draw_strategy"`
	TicketPrice              sql.NullString           `json:"ticket_price"`
	FreeTickets              int32                    `json:"free_tickets"`
	FreeTicketStartRange     sql.NullInt32            `json:"free_ticket_start_range"`
	FreeTicketEndRange       sql.NullInt32            `json:"free_ticket_end_range"`
	MaxTickets               sql.NullInt32            `json:"max_tickets"`
	TicketsSold              int32                    `json:"tickets_sold"`
	Attributes               json.RawMessage          `json:"attributes"`
	ImageUrls                []string                 `json:"image_urls"`
	DrawAt                   sql.NullTime             `json:"draw_at"`
	DrawnAt                  sql.NullTime             `json:"drawn_at"`
	CreatedBy                uuid.NullUUID            `json:"created_by"`
	CreatedAt                time.Time                `json:"created_at"`
	UpdatedAt                time.Time                `json:"updated_at"`
	CategoryName             string                   `json:"category_name"`
}

// Dashboard "active raffles" section.
func (q *Queries) ListActiveRafflesForNonprofit(ctx context.Context, arg ListActiveRafflesForNonprofitParams) ([]ListActiveRafflesForNonprofitRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRafflesForNonprofit, arg.NonprofitID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRafflesForNonprofitRow{}
	for rows.Next() {
		var i ListActiveRafflesForNonprofitRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryPath,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.TicketAssignmentStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.FreeTickets,
			&i.FreeTicketStartRange,
			&i.FreeTicketEndRange,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.DrawAt,
			&i.DrawnAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndingSoonRaffles = `-- name: ListEndingSoonRaffles :many
SELECT
    id, title, slug, description, status, ticket_strategy, draw_strategy, ticket_price, max_tickets, tickets_sold, draw_at, attributes, image_urls, category_path, nonprofit_id, category_id, category_name, category_slug, category_icon, category_depth
FROM
    v_active_raffles
WHERE
    draw_at IS NOT NULL
    AND draw_at > NOW()
ORDER BY
    draw_at ASC
LIMIT
    $1
`

func (q *Queries) ListEndingSoonRaffles(ctx context.Context, resultLimit int32) ([]VActiveRaffle, error) {
	rows, err := q.db.QueryContext(ctx, listEndingSoonRaffles, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VActiveRaffle{}
	for rows.Next() {
		var i VActiveRaffle
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.DrawAt,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.CategoryPath,
			&i.NonprofitID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryIcon,
			&i.CategoryDepth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedRaffles = `-- name: ListFeaturedRaffles :many
SELECT
    id, title, slug, description, status, ticket_strategy, draw_strategy, ticket_price, max_tickets, tickets_sold, draw_at, attributes, image_urls, category_path, nonprofit_id, category_id, category_name, category_slug, category_icon, category_depth
FROM
    v_active_raffles
ORDER BY
    tickets_sold DESC
LIMIT
    $1
`

// Hero / featured: active raffles with the most tickets sold.
func (q *Queries) ListFeaturedRaffles(ctx context.Context, resultLimit int32) ([]VActiveRaffle, error) {
	rows, err := q.db.QueryContext(ctx, listFeaturedRaffles, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VActiveRaffle{}
	for rows.Next() {
		var i VActiveRaffle
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.DrawAt,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.CategoryPath,
			&i.NonprofitID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryIcon,
			&i.CategoryDepth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRafflesByCategory = `-- name: ListRafflesByCategory :many
SELECT
    id, title, slug, description, status, ticket_strategy, draw_strategy, ticket_price, max_tickets, tickets_sold, draw_at, attributes, image_urls, category_path, nonprofit_id, category_id, category_name, category_slug, category_icon, category_depth
FROM
    v_active_raffles
WHERE
    category_path LIKE $1::text || '%'
ORDER BY
    tickets_sold DESC
LIMIT
    $3 OFFSET $2
`

type ListRafflesByCategoryParams struct {
	CategoryPathPrefix string `json:"category_path_prefix"`
	ResultOffset       int32  `json:"result_offset"`
	ResultLimit        int32  `json:"result_limit"`
}

// Browse a category subtree (path LIKE 'electronics%').
func (q *Queries) ListRafflesByCategory(ctx context.Context, arg ListRafflesByCategoryParams) ([]VActiveRaffle, error) {
	rows, err := q.db.QueryContext(ctx, listRafflesByCategory, arg.CategoryPathPrefix, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VActiveRaffle{}
	for rows.Next() {
		var i VActiveRaffle
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.DrawAt,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.CategoryPath,
			&i.NonprofitID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryIcon,
			&i.CategoryDepth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRafflesForNonprofit = `-- name: ListRafflesForNonprofit :many
SELECT
    ri.id, ri.category_id, ri.category_path, ri.title, ri.slug, ri.description, ri.status, ri.ticket_strategy, ri.ticket_assignment_strategy, ri.draw_strategy, ri.ticket_price, ri.free_tickets, ri.free_ticket_start_range, ri.free_ticket_end_range, ri.max_tickets, ri.tickets_sold, ri.attributes, ri.image_urls, ri.draw_at, ri.drawn_at, ri.created_by, ri.created_at, ri.updated_at,
    c.name AS category_name,
    c.icon AS category_icon
FROM
    raffle_items ri
    JOIN categories c ON c.id = ri.category_id
WHERE
    ri.created_by = $1
ORDER BY
    ri.created_at DESC
LIMIT
    $3 OFFSET $2
`

type ListRafflesForNonprofitParams struct {
	NonprofitID  uuid.NullUUID `json:"nonprofit_id"`
	ResultOffset int32         `json:"result_offset"`
	ResultLimit  int32         `json:"result_limit"`
}

type ListRafflesForNonprofitRow struct {
	ID                       uuid.UUID                `json:"id"`
	CategoryID               uuid.UUID                `json:"category_id"`
	CategoryPath             string                   `json:"category_path"`
	Title                    string                   `json:"title"`
	Slug                     sql.NullString           `json:"slug"`
	Description              sql.NullString           `json:"description"`
	Status                   RaffleItemStatus         `json:"status"`
	TicketStrategy           TicketStrategy           `json:"ticket_strategy"`
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	DrawStrategy             DrawStrategy             `json:"draw_strategy"`
	TicketPrice              sql.NullString           `json:"ticket_price"`
	FreeTickets              int32                    `json:"free_tickets"`
	FreeTicketStartRange     sql.NullInt32            `json:"free_ticket_start_range"`
	FreeTicketEndRange       sql.NullInt32            `json:"free_ticket_end_range"`
	MaxTickets               sql.NullInt32            `json:"max_tickets"`
	TicketsSold              int32                    `json:"tickets_sold"`
	Attributes               json.RawMessage          `json:"attributes"`
	ImageUrls                []string                 `json:"image_urls"`
	DrawAt                   sql.NullTime             `json:"draw_at"`
	DrawnAt                  sql.NullTime             `json:"drawn_at"`
	CreatedBy                uuid.NullUUID            `json:"created_by"`
	CreatedAt                time.Time                `json:"created_at"`
	UpdatedAt                time.Time                `json:"updated_at"`
	CategoryName             string                   `json:"category_name"`
	CategoryIcon             sql.NullString           `json:"category_icon"`
}

// ── Nonprofit's own raffles (manage screen) ───────────────────────────────────
func (q *Queries) ListRafflesForNonprofit(ctx context.Context, arg ListRafflesForNonprofitParams) ([]ListRafflesForNonprofitRow, error) {
	rows, err := q.db.QueryContext(ctx, listRafflesForNonprofit, arg.NonprofitID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRafflesForNonprofitRow{}
	for rows.Next() {
		var i ListRafflesForNonprofitRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryPath,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.TicketAssignmentStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.FreeTickets,
			&i.FreeTicketStartRange,
			&i.FreeTicketEndRange,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.DrawAt,
			&i.DrawnAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRafflesForNonprofitByStatus = `-- name: ListRafflesForNonprofitByStatus :many
SELECT
    ri.id, ri.category_id, ri.category_path, ri.title, ri.slug, ri.description, ri.status, ri.ticket_strategy, ri.ticket_assignment_strategy, ri.draw_strategy, ri.ticket_price, ri.free_tickets, ri.free_ticket_start_range, ri.free_ticket_end_range, ri.max_tickets, ri.tickets_sold, ri.attributes, ri.image_urls, ri.draw_at, ri.drawn_at, ri.created_by, ri.created_at, ri.updated_at,
    c.name AS category_name,
    c.icon AS category_icon
FROM
    raffle_items ri
    JOIN categories c ON c.id = ri.category_id
WHERE
    ri.created_by = $1
    AND ri.status = $2
ORDER BY
    ri.created_at DESC
LIMIT
    $4 OFFSET $3
`

type ListRafflesForNonprofitByStatusParams struct {
	NonprofitID  uuid.NullUUID    `json:"nonprofit_id"`
	Status       RaffleItemStatus `json:"status"`
	ResultOffset int32            `json:"result_offset"`
	ResultLimit  int32            `json:"result_limit"`
}

type ListRafflesForNonprofitByStatusRow struct {
	ID                       uuid.UUID                `json:"id"`
	CategoryID               uuid.UUID                `json:"category_id"`
	CategoryPath             string                   `json:"category_path"`
	Title                    string                   `json:"title"`
	Slug                     sql.NullString           `json:"slug"`
	Description              sql.NullString           `json:"description"`
	Status                   RaffleItemStatus         `json:"status"`
	TicketStrategy           TicketStrategy           `json:"ticket_strategy"`
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	DrawStrategy             DrawStrategy             `json:"draw_strategy"`
	TicketPrice              sql.NullString           `json:"ticket_price"`
	FreeTickets              int32                    `json:"free_tickets"`
	FreeTicketStartRange     sql.NullInt32            `json:"free_ticket_start_range"`
	FreeTicketEndRange       sql.NullInt32            `json:"free_ticket_end_range"`
	MaxTickets               sql.NullInt32            `json:"max_tickets"`
	TicketsSold              int32                    `json:"tickets_sold"`
	Attributes               json.RawMessage          `json:"attributes"`
	ImageUrls                []string                 `json:"image_urls"`
	DrawAt                   sql.NullTime             `json:"draw_at"`
	DrawnAt                  sql.NullTime             `json:"drawn_at"`
	CreatedBy                uuid.NullUUID            `json:"created_by"`
	CreatedAt                time.Time                `json:"created_at"`
	UpdatedAt                time.Time                `json:"updated_at"`
	CategoryName             string                   `json:"category_name"`
	CategoryIcon             sql.NullString           `json:"category_icon"`
}

func (q *Queries) ListRafflesForNonprofitByStatus(ctx context.Context, arg ListRafflesForNonprofitByStatusParams) ([]ListRafflesForNonprofitByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listRafflesForNonprofitByStatus,
		arg.NonprofitID,
		arg.Status,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRafflesForNonprofitByStatusRow{}
	for rows.Next() {
		var i ListRafflesForNonprofitByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryPath,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.TicketAssignmentStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.FreeTickets,
			&i.FreeTicketStartRange,
			&i.FreeTicketEndRange,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.DrawAt,
			&i.DrawnAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRafflesReadyToDraw = `-- name: ListRafflesReadyToDraw :many
SELECT
    id, category_id, category_path, title, slug, description, status, ticket_strategy, ticket_assignment_strategy, draw_strategy, ticket_price, free_tickets, free_ticket_start_range, free_ticket_end_range, max_tickets, tickets_sold, attributes, image_urls, draw_at, drawn_at, created_by, created_at, updated_at
FROM
    raffle_items
WHERE
    STATUS = 'active'
    AND draw_at IS NOT NULL
    AND draw_at <= NOW()
`

// For the draw worker: active raffles whose draw_at has passed.
func (q *Queries) ListRafflesReadyToDraw(ctx context.Context) ([]RaffleItem, error) {
	rows, err := q.db.QueryContext(ctx, listRafflesReadyToDraw)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RaffleItem{}
	for rows.Next() {
		var i RaffleItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryPath,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.TicketAssignmentStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.FreeTickets,
			&i.FreeTicketStartRange,
			&i.FreeTicketEndRange,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.DrawAt,
			&i.DrawnAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishRaffle = `-- name: PublishRaffle :one
UPDATE
    raffle_items
SET
    STATUS = 'active'
WHERE
    id = $1
    AND created_by = $2
    AND STATUS = 'draft'
RETURNING
    id, category_id, category_path, title, slug, description, status, ticket_strategy, ticket_assignment_strategy, draw_strategy, ticket_price, free_tickets, free_ticket_start_range, free_ticket_end_range, max_tickets, tickets_sold, attributes, image_urls, draw_at, drawn_at, created_by, created_at, updated_at
`

type PublishRaffleParams struct {
	RaffleID    uuid.UUID     `json:"raffle_id"`
	NonprofitID uuid.NullUUID `json:"nonprofit_id"`
}

func (q *Queries) PublishRaffle(ctx context.Context, arg PublishRaffleParams) (RaffleItem, error) {
	row := q.db.QueryRowContext(ctx, publishRaffle, arg.RaffleID, arg.NonprofitID)
	var i RaffleItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.CategoryPath,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.TicketStrategy,
		&i.TicketAssignmentStrategy,
		&i.DrawStrategy,
		&i.TicketPrice,
		&i.FreeTickets,
		&i.FreeTicketStartRange,
		&i.FreeTicketEndRange,
		&i.MaxTickets,
		&i.TicketsSold,
		&i.Attributes,
		pq.Array(&i.ImageUrls),
		&i.DrawAt,
		&i.DrawnAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchRaffles = `-- name: SearchRaffles :many
SELECT
    ri.id, ri.category_id, ri.category_path, ri.title, ri.slug, ri.description, ri.status, ri.ticket_strategy, ri.ticket_assignment_strategy, ri.draw_strategy, ri.ticket_price, ri.free_tickets, ri.free_ticket_start_range, ri.free_ticket_end_range, ri.max_tickets, ri.tickets_sold, ri.attributes, ri.image_urls, ri.draw_at, ri.drawn_at, ri.created_by, ri.created_at, ri.updated_at,
    c.name AS category_name,
    c.icon AS category_icon
FROM
    raffle_items ri
    JOIN categories c ON c.id = ri.category_id
WHERE
    ri.status = 'active'
    AND to_tsvector(
        'english',
        coalesce(ri.title, '') || ' ' || coalesce(ri.description, '')
    ) @@ plainto_tsquery('english', $1)
ORDER BY
    ri.tickets_sold DESC
LIMIT
    $3 OFFSET $2
`

type SearchRafflesParams struct {
	Query        string `json:"query"`
	ResultOffset int32  `json:"result_offset"`
	ResultLimit  int32  `json:"result_limit"`
}

type SearchRafflesRow struct {
	ID                       uuid.UUID                `json:"id"`
	CategoryID               uuid.UUID                `json:"category_id"`
	CategoryPath             string                   `json:"category_path"`
	Title                    string                   `json:"title"`
	Slug                     sql.NullString           `json:"slug"`
	Description              sql.NullString           `json:"description"`
	Status                   RaffleItemStatus         `json:"status"`
	TicketStrategy           TicketStrategy           `json:"ticket_strategy"`
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	DrawStrategy             DrawStrategy             `json:"draw_strategy"`
	TicketPrice              sql.NullString           `json:"ticket_price"`
	FreeTickets              int32                    `json:"free_tickets"`
	FreeTicketStartRange     sql.NullInt32            `json:"free_ticket_start_range"`
	FreeTicketEndRange       sql.NullInt32            `json:"free_ticket_end_range"`
	MaxTickets               sql.NullInt32            `json:"max_tickets"`
	TicketsSold              int32                    `json:"tickets_sold"`
	Attributes               json.RawMessage          `json:"attributes"`
	ImageUrls                []string                 `json:"image_urls"`
	DrawAt                   sql.NullTime             `json:"draw_at"`
	DrawnAt                  sql.NullTime             `json:"drawn_at"`
	CreatedBy                uuid.NullUUID            `json:"created_by"`
	CreatedAt                time.Time                `json:"created_at"`
	UpdatedAt                time.Time                `json:"updated_at"`
	CategoryName             string                   `json:"category_name"`
	CategoryIcon             sql.NullString           `json:"category_icon"`
}

// Full-text search on title + description.
func (q *Queries) SearchRaffles(ctx context.Context, arg SearchRafflesParams) ([]SearchRafflesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchRaffles, arg.Query, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRafflesRow{}
	for rows.Next() {
		var i SearchRafflesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryPath,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.TicketStrategy,
			&i.TicketAssignmentStrategy,
			&i.DrawStrategy,
			&i.TicketPrice,
			&i.FreeTickets,
			&i.FreeTicketStartRange,
			&i.FreeTicketEndRange,
			&i.MaxTickets,
			&i.TicketsSold,
			&i.Attributes,
			pq.Array(&i.ImageUrls),
			&i.DrawAt,
			&i.DrawnAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRaffleDrawAt = `-- name: SetRaffleDrawAt :one
UPDATE
    raffle_items
SET
    draw_at = $2
WHERE
    id = $1
RETURNING
    id, category_id, category_path, title, slug, description, status, ticket_strategy, ticket_assignment_strategy, draw_strategy, ticket_price, free_tickets, free_ticket_start_range, free_ticket_end_range, max_tickets, tickets_sold, attributes, image_urls, draw_at, drawn_at, created_by, created_at, updated_at
`

type SetRaffleDrawAtParams struct {
	ID     uuid.UUID    `json:"id"`
	DrawAt sql.NullTime `json:"draw_at"`
}

// Called when the raffle sells out and a draw is scheduled.
func (q *Queries) SetRaffleDrawAt(ctx context.Context, arg SetRaffleDrawAtParams) (RaffleItem, error) {
	row := q.db.QueryRowContext(ctx, setRaffleDrawAt, arg.ID, arg.DrawAt)
	var i RaffleItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.CategoryPath,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.TicketStrategy,
		&i.TicketAssignmentStrategy,
		&i.DrawStrategy,
		&i.TicketPrice,
		&i.FreeTickets,
		&i.FreeTicketStartRange,
		&i.FreeTicketEndRange,
		&i.MaxTickets,
		&i.TicketsSold,
		&i.Attributes,
		pq.Array(&i.ImageUrls),
		&i.DrawAt,
		&i.DrawnAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRaffleStatus = `-- name: SetRaffleStatus :one
UPDATE
    raffle_items
SET
    STATUS = $2
WHERE
    id = $1
RETURNING
    id, category_id, category_path, title, slug, description, status, ticket_strategy, ticket_assignment_strategy, draw_strategy, ticket_price, free_tickets, free_ticket_start_range, free_ticket_end_range, max_tickets, tickets_sold, attributes, image_urls, draw_at, drawn_at, created_by, created_at, updated_at
`

type SetRaffleStatusParams struct {
	ID     uuid.UUID        `json:"id"`
	Status RaffleItemStatus `json:"status"`
}

func (q *Queries) SetRaffleStatus(ctx context.Context, arg SetRaffleStatusParams) (RaffleItem, error) {
	row := q.db.QueryRowContext(ctx, setRaffleStatus, arg.ID, arg.Status)
	var i RaffleItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.CategoryPath,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.TicketStrategy,
		&i.TicketAssignmentStrategy,
		&i.DrawStrategy,
		&i.TicketPrice,
		&i.FreeTickets,
		&i.FreeTicketStartRange,
		&i.FreeTicketEndRange,
		&i.MaxTickets,
		&i.TicketsSold,
		&i.Attributes,
		pq.Array(&i.ImageUrls),
		&i.DrawAt,
		&i.DrawnAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const slugExists = `-- name: SlugExists :one
SELECT
    EXISTS(
        SELECT
            1
        FROM
            raffle_items
        WHERE
            slug = $1
    ) AS EXISTS
`

func (q *Queries) SlugExists(ctx context.Context, slug sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRaffle = `-- name: UpdateRaffle :one
UPDATE
    raffle_items
SET
    title = $1,
    description = $2,
    ticket_strategy = $3,
    ticket_assignment_strategy = $4,
    draw_strategy = $5,
    ticket_price = $6,
    free_tickets = $7,
    free_ticket_start_range = $8,
    free_ticket_end_range = $9,
    max_tickets = $10,
    attributes = $11,
    image_urls = $12
WHERE
    id = $13
    AND created_by = $14
RETURNING
    id, category_id, category_path, title, slug, description, status, ticket_strategy, ticket_assignment_strategy, draw_strategy, ticket_price, free_tickets, free_ticket_start_range, free_ticket_end_range, max_tickets, tickets_sold, attributes, image_urls, draw_at, drawn_at, created_by, created_at, updated_at
`

type UpdateRaffleParams struct {
	Title                    string                   `json:"title"`
	Description              sql.NullString           `json:"description"`
	TicketStrategy           TicketStrategy           `json:"ticket_strategy"`
	TicketAssignmentStrategy TicketAssignmentStrategy `json:"ticket_assignment_strategy"`
	DrawStrategy             DrawStrategy             `json:"draw_strategy"`
	TicketPrice              sql.NullString           `json:"ticket_price"`
	FreeTickets              int32                    `json:"free_tickets"`
	FreeTicketStartRange     sql.NullInt32            `json:"free_ticket_start_range"`
	FreeTicketEndRange       sql.NullInt32            `json:"free_ticket_end_range"`
	MaxTickets               sql.NullInt32            `json:"max_tickets"`
	Attributes               json.RawMessage          `json:"attributes"`
	ImageUrls                []string                 `json:"image_urls"`
	RaffleID                 uuid.UUID                `json:"raffle_id"`
	NonprofitID              uuid.NullUUID            `json:"nonprofit_id"`
}

func (q *Queries) UpdateRaffle(ctx context.Context, arg UpdateRaffleParams) (RaffleItem, error) {
	row := q.db.QueryRowContext(ctx, updateRaffle,
		arg.Title,
		arg.Description,
		arg.TicketStrategy,
		arg.TicketAssignmentStrategy,
		arg.DrawStrategy,
		arg.TicketPrice,
		arg.FreeTickets,
		arg.FreeTicketStartRange,
		arg.FreeTicketEndRange,
		arg.MaxTickets,
		arg.Attributes,
		pq.Array(arg.ImageUrls),
		arg.RaffleID,
		arg.NonprofitID,
	)
	var i RaffleItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.CategoryPath,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.TicketStrategy,
		&i.TicketAssignmentStrategy,
		&i.DrawStrategy,
		&i.TicketPrice,
		&i.FreeTickets,
		&i.FreeTicketStartRange,
		&i.FreeTicketEndRange,
		&i.MaxTickets,
		&i.TicketsSold,
		&i.Attributes,
		pq.Array(&i.ImageUrls),
		&i.DrawAt,
		&i.DrawnAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
