// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countParticipantsForRaffle = `-- name: CountParticipantsForRaffle :one
SELECT
    COUNT(DISTINCT user_id)::INT AS count
FROM
    tickets
WHERE
    raffle_item_id = $1
`

func (q *Queries) CountParticipantsForRaffle(ctx context.Context, raffleItemID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countParticipantsForRaffle, raffleItemID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO
    orders (
        user_id,
        raffle_item_id,
        ticket_count,
        subtotal_cents,
        donation_cents,
        total_cents,
        processor,
        processor_payment_id,
        STATUS,
        receipt_number
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id, user_id, raffle_item_id, ticket_count, subtotal_cents, donation_cents, total_cents, processor, processor_payment_id, status, receipt_number, created_at, updated_at
`

type CreateOrderParams struct {
	UserID             uuid.UUID      `json:"user_id"`
	RaffleItemID       uuid.UUID      `json:"raffle_item_id"`
	TicketCount        int32          `json:"ticket_count"`
	SubtotalCents      int32          `json:"subtotal_cents"`
	DonationCents      int32          `json:"donation_cents"`
	TotalCents         int32          `json:"total_cents"`
	Processor          string         `json:"processor"`
	ProcessorPaymentID sql.NullString `json:"processor_payment_id"`
	Status             string         `json:"status"`
	ReceiptNumber      sql.NullString `json:"receipt_number"`
}

// ── Orders ───────────────────────────────────────────────────────────────────
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.RaffleItemID,
		arg.TicketCount,
		arg.SubtotalCents,
		arg.DonationCents,
		arg.TotalCents,
		arg.Processor,
		arg.ProcessorPaymentID,
		arg.Status,
		arg.ReceiptNumber,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RaffleItemID,
		&i.TicketCount,
		&i.SubtotalCents,
		&i.DonationCents,
		&i.TotalCents,
		&i.Processor,
		&i.ProcessorPaymentID,
		&i.Status,
		&i.ReceiptNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO
    tickets (
        raffle_item_id,
        user_id,
        order_id,
        ticket_number,
        price_paid
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5
    )
RETURNING
    id, raffle_item_id, user_id, order_id, ticket_number, price_paid, purchased_at
`

type CreateTicketParams struct {
	RaffleItemID uuid.UUID     `json:"raffle_item_id"`
	UserID       uuid.UUID     `json:"user_id"`
	OrderID      uuid.NullUUID `json:"order_id"`
	TicketNumber sql.NullInt32 `json:"ticket_number"`
	PricePaid    string        `json:"price_paid"`
}

// ── Tickets ──────────────────────────────────────────────────────────────────
// ticket_number and price_paid are auto-filled by the assign_ticket_number trigger
// when passed as NULL / 0 (system assignment). For user_picks, pass them explicitly.
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, createTicket,
		arg.RaffleItemID,
		arg.UserID,
		arg.OrderID,
		arg.TicketNumber,
		arg.PricePaid,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.RaffleItemID,
		&i.UserID,
		&i.OrderID,
		&i.TicketNumber,
		&i.PricePaid,
		&i.PurchasedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    id, user_id, raffle_item_id, ticket_count, subtotal_cents, donation_cents, total_cents, processor, processor_payment_id, status, receipt_number, created_at, updated_at
FROM
    orders
WHERE
    id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RaffleItemID,
		&i.TicketCount,
		&i.SubtotalCents,
		&i.DonationCents,
		&i.TotalCents,
		&i.Processor,
		&i.ProcessorPaymentID,
		&i.Status,
		&i.ReceiptNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByReceiptNumber = `-- name: GetOrderByReceiptNumber :one
SELECT
    o.id, o.user_id, o.raffle_item_id, o.ticket_count, o.subtotal_cents, o.donation_cents, o.total_cents, o.processor, o.processor_payment_id, o.status, o.receipt_number, o.created_at, o.updated_at,
    ri.title AS raffle_title,
    n.name AS nonprofit_name,
    n.ein AS nonprofit_ein
FROM
    orders o
    JOIN raffle_items ri ON ri.id = o.raffle_item_id
    LEFT JOIN nonprofits n ON n.id = ri.created_by
WHERE
    o.receipt_number = $1
`

type GetOrderByReceiptNumberRow struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.UUID      `json:"user_id"`
	RaffleItemID       uuid.UUID      `json:"raffle_item_id"`
	TicketCount        int32          `json:"ticket_count"`
	SubtotalCents      int32          `json:"subtotal_cents"`
	DonationCents      int32          `json:"donation_cents"`
	TotalCents         int32          `json:"total_cents"`
	Processor          string         `json:"processor"`
	ProcessorPaymentID sql.NullString `json:"processor_payment_id"`
	Status             string         `json:"status"`
	ReceiptNumber      sql.NullString `json:"receipt_number"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	RaffleTitle        string         `json:"raffle_title"`
	NonprofitName      sql.NullString `json:"nonprofit_name"`
	NonprofitEin       sql.NullString `json:"nonprofit_ein"`
}

func (q *Queries) GetOrderByReceiptNumber(ctx context.Context, receiptNumber sql.NullString) (GetOrderByReceiptNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderByReceiptNumber, receiptNumber)
	var i GetOrderByReceiptNumberRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RaffleItemID,
		&i.TicketCount,
		&i.SubtotalCents,
		&i.DonationCents,
		&i.TotalCents,
		&i.Processor,
		&i.ProcessorPaymentID,
		&i.Status,
		&i.ReceiptNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RaffleTitle,
		&i.NonprofitName,
		&i.NonprofitEin,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT
    id, raffle_item_id, user_id, order_id, ticket_number, price_paid, purchased_at
FROM
    tickets
WHERE
    id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.RaffleItemID,
		&i.UserID,
		&i.OrderID,
		&i.TicketNumber,
		&i.PricePaid,
		&i.PurchasedAt,
	)
	return i, err
}

const getUserTicketStats = `-- name: GetUserTicketStats :one
SELECT
    COUNT(*)::INT AS total_tickets_purchased,
    COUNT(DISTINCT raffle_item_id)::INT AS total_raffles_entered,
    COALESCE(SUM(price_paid), 0)::NUMERIC AS total_spent
FROM
    tickets
WHERE
    user_id = $1
`

type GetUserTicketStatsRow struct {
	TotalTicketsPurchased int32  `json:"total_tickets_purchased"`
	TotalRafflesEntered   int32  `json:"total_raffles_entered"`
	TotalSpent            string `json:"total_spent"`
}

func (q *Queries) GetUserTicketStats(ctx context.Context, userID uuid.UUID) (GetUserTicketStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserTicketStats, userID)
	var i GetUserTicketStatsRow
	err := row.Scan(&i.TotalTicketsPurchased, &i.TotalRafflesEntered, &i.TotalSpent)
	return i, err
}

const isTicketNumberTaken = `-- name: IsTicketNumberTaken :one
SELECT
    EXISTS(
        SELECT
            1
        FROM
            tickets
        WHERE
            raffle_item_id = $1
            AND ticket_number = $2
    ) AS taken
`

type IsTicketNumberTakenParams struct {
	RaffleItemID uuid.UUID `json:"raffle_item_id"`
	TicketNumber int32     `json:"ticket_number"`
}

func (q *Queries) IsTicketNumberTaken(ctx context.Context, arg IsTicketNumberTakenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTicketNumberTaken, arg.RaffleItemID, arg.TicketNumber)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const listAvailableTicketNumbers = `-- name: ListAvailableTicketNumbers :many
SELECT
    n AS ticket_number
FROM
    generate_series(1, $1::INT) AS n
WHERE
    n NOT IN (
        SELECT
            ticket_number
        FROM
            tickets
        WHERE
            raffle_item_id = $2
    )
ORDER BY
    n
`

type ListAvailableTicketNumbersParams struct {
	MaxTickets   int32     `json:"max_tickets"`
	RaffleItemID uuid.UUID `json:"raffle_item_id"`
}

// For user_picks assignment: which numbers in 1..max are still free.
func (q *Queries) ListAvailableTicketNumbers(ctx context.Context, arg ListAvailableTicketNumbersParams) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableTicketNumbers, arg.MaxTickets, arg.RaffleItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var ticket_number sql.NullString
		if err := rows.Scan(&ticket_number); err != nil {
			return nil, err
		}
		items = append(items, ticket_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForUser = `-- name: ListOrdersForUser :many
SELECT
    o.id, o.user_id, o.raffle_item_id, o.ticket_count, o.subtotal_cents, o.donation_cents, o.total_cents, o.processor, o.processor_payment_id, o.status, o.receipt_number, o.created_at, o.updated_at,
    ri.title AS raffle_title
FROM
    orders o
    JOIN raffle_items ri ON ri.id = o.raffle_item_id
WHERE
    o.user_id = $1
ORDER BY
    o.created_at DESC
LIMIT
    $3 OFFSET $2
`

type ListOrdersForUserParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

type ListOrdersForUserRow struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.UUID      `json:"user_id"`
	RaffleItemID       uuid.UUID      `json:"raffle_item_id"`
	TicketCount        int32          `json:"ticket_count"`
	SubtotalCents      int32          `json:"subtotal_cents"`
	DonationCents      int32          `json:"donation_cents"`
	TotalCents         int32          `json:"total_cents"`
	Processor          string         `json:"processor"`
	ProcessorPaymentID sql.NullString `json:"processor_payment_id"`
	Status             string         `json:"status"`
	ReceiptNumber      sql.NullString `json:"receipt_number"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	RaffleTitle        string         `json:"raffle_title"`
}

func (q *Queries) ListOrdersForUser(ctx context.Context, arg ListOrdersForUserParams) ([]ListOrdersForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersForUser, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersForUserRow{}
	for rows.Next() {
		var i ListOrdersForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RaffleItemID,
			&i.TicketCount,
			&i.SubtotalCents,
			&i.DonationCents,
			&i.TotalCents,
			&i.Processor,
			&i.ProcessorPaymentID,
			&i.Status,
			&i.ReceiptNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RaffleTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketNumbersForRaffle = `-- name: ListTicketNumbersForRaffle :many
SELECT
    ticket_number,
    id AS ticket_id,
    user_id
FROM
    tickets
WHERE
    raffle_item_id = $1
ORDER BY
    ticket_number
`

type ListTicketNumbersForRaffleRow struct {
	TicketNumber int32     `json:"ticket_number"`
	TicketID     uuid.UUID `json:"ticket_id"`
	UserID       uuid.UUID `json:"user_id"`
}

// For the draw engine: all numbers in order (input to the deterministic shuffle).
func (q *Queries) ListTicketNumbersForRaffle(ctx context.Context, raffleItemID uuid.UUID) ([]ListTicketNumbersForRaffleRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketNumbersForRaffle, raffleItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketNumbersForRaffleRow{}
	for rows.Next() {
		var i ListTicketNumbersForRaffleRow
		if err := rows.Scan(&i.TicketNumber, &i.TicketID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsForRaffle = `-- name: ListTicketsForRaffle :many
SELECT
    id, raffle_item_id, user_id, order_id, ticket_number, price_paid, purchased_at
FROM
    tickets
WHERE
    raffle_item_id = $1
ORDER BY
    ticket_number
`

func (q *Queries) ListTicketsForRaffle(ctx context.Context, raffleItemID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsForRaffle, raffleItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.RaffleItemID,
			&i.UserID,
			&i.OrderID,
			&i.TicketNumber,
			&i.PricePaid,
			&i.PurchasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTicketsGrouped = `-- name: ListUserTicketsGrouped :many
SELECT
    ri.id AS raffle_item_id,
    ri.title,
    ri.status,
    ri.draw_at,
    ri.image_urls,
    n.name AS nonprofit_name,
    ARRAY_AGG(
        t.ticket_number
        ORDER BY
            t.ticket_number
    )::INT[] AS ticket_numbers,
    COUNT(t.id)::INT AS ticket_count,
    SUM(t.price_paid)::NUMERIC AS total_spent,
    MAX(t.purchased_at)::TIMESTAMPTZ AS purchased_at
FROM
    tickets t
    JOIN raffle_items ri ON ri.id = t.raffle_item_id
    LEFT JOIN nonprofits n ON n.id = ri.created_by
WHERE
    t.user_id = $1
GROUP BY
    ri.id,
    ri.title,
    ri.status,
    ri.draw_at,
    ri.image_urls,
    n.name
ORDER BY
    ri.draw_at NULLS LAST
`

type ListUserTicketsGroupedRow struct {
	RaffleItemID  uuid.UUID        `json:"raffle_item_id"`
	Title         string           `json:"title"`
	Status        RaffleItemStatus `json:"status"`
	DrawAt        sql.NullTime     `json:"draw_at"`
	ImageUrls     []string         `json:"image_urls"`
	NonprofitName sql.NullString   `json:"nonprofit_name"`
	TicketNumbers []int32          `json:"ticket_numbers"`
	TicketCount   int32            `json:"ticket_count"`
	TotalSpent    string           `json:"total_spent"`
	PurchasedAt   time.Time        `json:"purchased_at"`
}

// ── User's tickets (My Tickets screen) ────────────────────────────────────────
// One row per raffle the user has tickets in, with their numbers aggregated.
func (q *Queries) ListUserTicketsGrouped(ctx context.Context, userID uuid.UUID) ([]ListUserTicketsGroupedRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserTicketsGrouped, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTicketsGroupedRow{}
	for rows.Next() {
		var i ListUserTicketsGroupedRow
		if err := rows.Scan(
			&i.RaffleItemID,
			&i.Title,
			&i.Status,
			&i.DrawAt,
			pq.Array(&i.ImageUrls),
			&i.NonprofitName,
			pq.Array(&i.TicketNumbers),
			&i.TicketCount,
			&i.TotalSpent,
			&i.PurchasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPaid = `-- name: MarkOrderPaid :one
UPDATE
    orders
SET
    STATUS = 'paid',
    processor_payment_id = $2
WHERE
    id = $1
RETURNING
    id, user_id, raffle_item_id, ticket_count, subtotal_cents, donation_cents, total_cents, processor, processor_payment_id, status, receipt_number, created_at, updated_at
`

type MarkOrderPaidParams struct {
	ID                 uuid.UUID      `json:"id"`
	ProcessorPaymentID sql.NullString `json:"processor_payment_id"`
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, markOrderPaid, arg.ID, arg.ProcessorPaymentID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RaffleItemID,
		&i.TicketCount,
		&i.SubtotalCents,
		&i.DonationCents,
		&i.TotalCents,
		&i.Processor,
		&i.ProcessorPaymentID,
		&i.Status,
		&i.ReceiptNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
