// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verifications.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createNonprofitVerification = `-- name: CreateNonprofitVerification :one

INSERT INTO
    nonprofit_verifications (
        nonprofit_id,
        "isVerified",
        "verificationMethod",
        "exemptStatus",
        subsection,
        "nteeCd",
        "rulingDate",
        foundation
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id, nonprofit_id, "isVerified", "verificationMethod", "exemptStatus", subsection, "nteeCd", "rulingDate", updated_at, created_at, foundation
`

type CreateNonprofitVerificationParams struct {
	NonprofitID        uuid.UUID      `json:"nonprofit_id"`
	IsVerified         sql.NullBool   `json:"isVerified"`
	VerificationMethod sql.NullString `json:"verificationMethod"`
	ExemptStatus       sql.NullInt32  `json:"exemptStatus"`
	Subsection         sql.NullInt32  `json:"subsection"`
	NteeCd             sql.NullString `json:"nteeCd"`
	RulingDate         sql.NullTime   `json:"rulingDate"`
	Foundation         sql.NullInt32  `json:"foundation"`
}

// Verification + fee-flag queries. Place this file in your sqlc queries
// directory (alongside the nonprofits queries) and run `sqlc generate`.
// Records a verification attempt. We insert a new row each time (history);
// GetNonprofitVerification already returns the most recent one.
func (q *Queries) CreateNonprofitVerification(ctx context.Context, arg CreateNonprofitVerificationParams) (NonprofitVerification, error) {
	row := q.db.QueryRowContext(ctx, createNonprofitVerification,
		arg.NonprofitID,
		arg.IsVerified,
		arg.VerificationMethod,
		arg.ExemptStatus,
		arg.Subsection,
		arg.NteeCd,
		arg.RulingDate,
		arg.Foundation,
	)
	var i NonprofitVerification
	err := row.Scan(
		&i.ID,
		&i.NonprofitID,
		&i.IsVerified,
		&i.VerificationMethod,
		&i.ExemptStatus,
		&i.Subsection,
		&i.NteeCd,
		&i.RulingDate,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Foundation,
	)
	return i, err
}

const setNonprofitEIN = `-- name: SetNonprofitEIN :one
UPDATE
    nonprofits
SET
    ein = $2
WHERE
    id = $1
RETURNING
    id, name, slug, description, image, address, phone, ein, "hasToPay", website, categories, follower_count, total_raised_cents, raffles_run, created_at, updated_at
`

type SetNonprofitEINParams struct {
	ID  uuid.UUID      `json:"id"`
	Ein sql.NullString `json:"ein"`
}

func (q *Queries) SetNonprofitEIN(ctx context.Context, arg SetNonprofitEINParams) (Nonprofit, error) {
	row := q.db.QueryRowContext(ctx, setNonprofitEIN, arg.ID, arg.Ein)
	var i Nonprofit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Address,
		&i.Phone,
		&i.Ein,
		&i.HasToPay,
		&i.Website,
		pq.Array(&i.Categories),
		&i.FollowerCount,
		&i.TotalRaisedCents,
		&i.RafflesRun,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setNonprofitHasToPay = `-- name: SetNonprofitHasToPay :one
UPDATE
    nonprofits
SET
    "hasToPay" = $2
WHERE
    id = $1
RETURNING
    id, name, slug, description, image, address, phone, ein, "hasToPay", website, categories, follower_count, total_raised_cents, raffles_run, created_at, updated_at
`

type SetNonprofitHasToPayParams struct {
	ID       uuid.UUID `json:"id"`
	HasToPay bool      `json:"hasToPay"`
}

func (q *Queries) SetNonprofitHasToPay(ctx context.Context, arg SetNonprofitHasToPayParams) (Nonprofit, error) {
	row := q.db.QueryRowContext(ctx, setNonprofitHasToPay, arg.ID, arg.HasToPay)
	var i Nonprofit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Address,
		&i.Phone,
		&i.Ein,
		&i.HasToPay,
		&i.Website,
		pq.Array(&i.Categories),
		&i.FollowerCount,
		&i.TotalRaisedCents,
		&i.RafflesRun,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
